package com.chrismin13.additionsapi.utils;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public class MaterialUtils {

	public static boolean isInstantlyBreakable(Material material) {
		float strength = getHardness(material);
		if (strength == 0F)
			return true;
		return false;
	}

	/**
	 * Retrieve the base damage of the given item.
	 * 
	 * @param stack
	 *            - the stack.
	 * @return The base damage.
	 */
	public static float getBaseDamage(ItemStack stack) {
		return getBaseDamage(stack.getType());
	}

	/**
	 * Retrieve the base damage of the given item.
	 * 
	 * @param material
	 *            - the material that you want the base damage for.
	 * @return The base damage.
	 */
	@SuppressWarnings("deprecation")
	public static float getBaseDamage(Material material) {
		// Yes - we have to hard code these values. Cannot use
		// Operation.ADD_PERCENTAGE either.
		switch (material) {
		// Swords
		case LEGACY_WOOD_SWORD:
		case WOODEN_SWORD:
			return 4F;
		case LEGACY_GOLD_SWORD:
		case GOLDEN_SWORD:
			return 4F;
		case LEGACY_STONE_SWORD:
		case STONE_SWORD:
			return 5F;
		case LEGACY_IRON_SWORD:
		case IRON_SWORD:
			return 6F;
		case LEGACY_DIAMOND_SWORD:
		case DIAMOND_SWORD:
			return 7F;
		// Axe
		case LEGACY_WOOD_AXE:
		case WOODEN_AXE:
			return 7F;
		case LEGACY_GOLD_AXE:
		case GOLDEN_AXE:
			return 7F;
		case LEGACY_STONE_AXE:
		case STONE_AXE:
			return 9F;
		case LEGACY_IRON_AXE:
		case IRON_AXE:
			return 9F;
		case LEGACY_DIAMOND_AXE:
		case DIAMOND_AXE:
			return 9F;
		// Pickaxe
		case LEGACY_WOOD_PICKAXE:
		case WOODEN_PICKAXE:
			return 2F;
		case LEGACY_STONE_PICKAXE:
		case STONE_PICKAXE:
			return 3F;
		case LEGACY_IRON_PICKAXE:
		case IRON_PICKAXE:
			return 4F;
		case LEGACY_GOLD_PICKAXE:
		case GOLDEN_PICKAXE:
			return 2F;
		case LEGACY_DIAMOND_PICKAXE:
		case DIAMOND_PICKAXE:
			return 5F;
		// Spades
		case LEGACY_WOOD_SPADE:
		case WOODEN_SHOVEL:
			return 2.5F;
		case LEGACY_STONE_SPADE:
		case STONE_SHOVEL:
			return 3.5F;
		case LEGACY_IRON_SPADE:
		case IRON_SHOVEL:
			return 4.5F;
		case LEGACY_GOLD_SPADE:
		case GOLDEN_SHOVEL:
			return 2.5F;
		case LEGACY_DIAMOND_SPADE:
		case DIAMOND_SHOVEL:
			return 5.5F;
		// Hoes
		case LEGACY_WOOD_HOE:
		case WOODEN_HOE:
			return 1F;
		case LEGACY_STONE_HOE:
		case STONE_HOE:
			return 1F;
		case LEGACY_IRON_HOE:
		case IRON_HOE:
			return 1F;
		case LEGACY_GOLD_HOE:
		case GOLDEN_HOE:
			return 1F;
		case LEGACY_DIAMOND_HOE:
		case DIAMOND_HOE:
			return 1F;
		default:
			return 1F;

		}
	}

	/**
	 * Retrieve the base damage of the given item.
	 * 
	 * @param stack
	 *            - the stack.
	 * @return The base damage.
	 */
	public static float getBaseSpeed(ItemStack stack) {
		return getBaseSpeed(stack.getType());
	}

	/**
	 * Retrieve the base damage of the given item.
	 * 
	 * @param material
	 *            - the material.
	 * @return The base damage.
	 */
	@SuppressWarnings("deprecation")
	public static float getBaseSpeed(Material material) {
		// Yes - we have to hard code these values. Cannot use
		// Operation.ADD_PERCENTAGE either.
		switch (material) {
		// Swords
		case LEGACY_WOOD_SWORD:
		case WOODEN_SWORD:
		case LEGACY_GOLD_SWORD:
		case GOLDEN_SWORD:
		case LEGACY_STONE_SWORD:
		case STONE_SWORD:
		case LEGACY_IRON_SWORD:
		case IRON_SWORD:
		case LEGACY_DIAMOND_SWORD:
		case DIAMOND_SWORD:
			return 1.6F;
		// Axe
		case LEGACY_WOOD_AXE:
		case WOODEN_AXE:
			return 0.8F;
		case LEGACY_GOLD_AXE:
		case GOLDEN_AXE:
			return 1F;
		case LEGACY_STONE_AXE:
		case STONE_AXE:
			return 0.8F;
		case LEGACY_IRON_AXE:
		case IRON_AXE:
			return 0.9F;
		case LEGACY_DIAMOND_AXE:
		case DIAMOND_AXE:
			return 1F;
		// Pickaxe
		case LEGACY_WOOD_PICKAXE:
		case WOODEN_PICKAXE:
		case LEGACY_STONE_PICKAXE:
		case STONE_PICKAXE:
		case LEGACY_IRON_PICKAXE:
		case IRON_PICKAXE:
		case LEGACY_GOLD_PICKAXE:
		case GOLDEN_PICKAXE:
		case LEGACY_DIAMOND_PICKAXE:
		case DIAMOND_PICKAXE:
			return 1.2F;
		// Spades
		case LEGACY_WOOD_SPADE:
		case WOODEN_SHOVEL:
		case LEGACY_STONE_SPADE:
		case STONE_SHOVEL:
		case LEGACY_IRON_SPADE:
		case IRON_SHOVEL:
		case LEGACY_GOLD_SPADE:
		case GOLDEN_SHOVEL:
		case LEGACY_DIAMOND_SPADE:
		case DIAMOND_SHOVEL:
			return 1F;
		// Hoes
		case LEGACY_WOOD_HOE:
		case WOODEN_HOE:
			return 1F;
		case LEGACY_STONE_HOE:
		case STONE_HOE:
			return 2F;
		case LEGACY_IRON_HOE:
		case IRON_HOE:
			return 3F;
		case LEGACY_GOLD_HOE:
		case GOLDEN_HOE:
			return 1F;
		case LEGACY_DIAMOND_HOE:
		case DIAMOND_HOE:
			return 4F;
		default:
			return 4F;

		}
	}

	/**
	 * Retrieve the base armor of the given armor.
	 * 
	 * @param stack
	 *            - the stack.
	 * @return The base damage.
	 */
	public static float getBaseArmor(ItemStack stack) {
		return getBaseArmor(stack.getType());
	}

	/**
	 * Retrieve the base armor of the given armor.
	 * 
	 * @param material
	 *            - the material.
	 * @return The base damage.
	 */
	@SuppressWarnings("deprecation")
	public static float getBaseArmor(Material material) {
		// Yes - we have to hard code these values. Cannot use
		// Operation.ADD_PERCENTAGE either.
		switch (material) {
		// Leather Armor
		case LEGACY_LEATHER_HELMET:
		case LEATHER_HELMET:
			return 1F;
		case LEGACY_LEATHER_CHESTPLATE:
		case LEATHER_CHESTPLATE:
			return 3F;
		case LEGACY_LEATHER_LEGGINGS:
		case LEATHER_LEGGINGS:
			return 2F;
		case LEGACY_LEATHER_BOOTS:
		case LEATHER_BOOTS:
			return 1F;
		// Chainmail Armor
		case LEGACY_CHAINMAIL_HELMET:
		case CHAINMAIL_HELMET:
			return 2F;
		case LEGACY_CHAINMAIL_CHESTPLATE:
		case CHAINMAIL_CHESTPLATE:
			return 5F;
		case LEGACY_CHAINMAIL_LEGGINGS:
		case CHAINMAIL_LEGGINGS:
			return 4F;
		case LEGACY_CHAINMAIL_BOOTS:
		case CHAINMAIL_BOOTS:
			return 1F;
		// Iron Armor
		case LEGACY_IRON_HELMET:
		case IRON_HELMET:
			return 2F;
		case LEGACY_IRON_CHESTPLATE:
		case IRON_CHESTPLATE:
			return 6F;
		case LEGACY_IRON_LEGGINGS:
		case IRON_LEGGINGS:
			return 5F;
		case LEGACY_IRON_BOOTS:
		case IRON_BOOTS:
			return 2F;
		// Golden Armor
		case LEGACY_GOLD_HELMET:
		case GOLDEN_HELMET:
			return 2F;
		case LEGACY_GOLD_CHESTPLATE:
		case GOLDEN_CHESTPLATE:
			return 5F;
		case LEGACY_GOLD_LEGGINGS:
		case GOLDEN_LEGGINGS:
			return 4F;
		case LEGACY_GOLD_BOOTS:
		case GOLDEN_BOOTS:
			return 1F;
		// Diamond Armor
		case LEGACY_DIAMOND_HELMET:
		case DIAMOND_HELMET:
			return 3F;
		case LEGACY_DIAMOND_CHESTPLATE:
		case DIAMOND_CHESTPLATE:
			return 8F;
		case LEGACY_DIAMOND_LEGGINGS:
		case DIAMOND_LEGGINGS:
			return 6F;
		case LEGACY_DIAMOND_BOOTS:
		case DIAMOND_BOOTS:
			return 3F;
		default:
			return 0F;

		}
	}

	/**
	 * Retrieve the base armor toughness of the given item.
	 * 
	 * @param stack
	 *            - the stack.
	 * @return The base damage.
	 */
	public static float getBaseArmorToughness(ItemStack stack) {
		return getBaseArmorToughness(stack.getType());
	}

	/**
	 * Retrieve the base armor toughness of the given item.
	 * 
	 * @param material
	 *            - the material.
	 * @return The base damage.
	 */
	// TODO: Disable for under 1.9.1
	@SuppressWarnings("deprecation")
	public static float getBaseArmorToughness(Material material) {
		// Yes - we have to hard code these values. Cannot use
		// Operation.ADD_PERCENTAGE either.
		switch (material) {
		// Diamond Armor
		case LEGACY_DIAMOND_HELMET:
		case DIAMOND_HELMET:
			return 2F;
		case LEGACY_DIAMOND_CHESTPLATE:
		case DIAMOND_CHESTPLATE:
			return 2F;
		case LEGACY_DIAMOND_LEGGINGS:
		case DIAMOND_LEGGINGS:
			return 2F;
		case LEGACY_DIAMOND_BOOTS:
		case DIAMOND_BOOTS:
			return 2F;
		default:
			return 0F;

		}
	}

	/**
	 * Obtains the block's hardness level (also mentioned as "strength"). This
	 * number is used to calculate the time required to break each block.
	 *
	 * @return the hardness of that material.
	 */
	@SuppressWarnings("deprecation")
	public static float getHardness(Material material) {
		try {
			return material.getHardness();
		} catch (Exception e) {
			switch (material) {
			// <editor-fold defaultstate="collapsed" desc="getBlockHardness">
			case BARRIER:
			case BEDROCK:
			case CHAIN_COMMAND_BLOCK:
			case COMMAND_BLOCK:
			case END_GATEWAY:
			case END_PORTAL:
			case END_PORTAL_FRAME:
			case MOVING_PISTON:
			case NETHER_PORTAL:
			case REPEATING_COMMAND_BLOCK:
			case STRUCTURE_BLOCK:
				return -1.0F;
			case ACACIA_BOAT:
			case ACACIA_SAPLING:
			case AIR:
			case ALLIUM:
			case APPLE:
			case ARMOR_STAND:
			case ARROW:
			case ATTACHED_MELON_STEM:
			case ATTACHED_PUMPKIN_STEM:
			case AZURE_BLUET:
			case BAKED_POTATO:
			case BAT_SPAWN_EGG:
			case BEEF:
			case BEETROOT:
			case BEETROOTS:
			case BEETROOT_SEEDS:
			case BEETROOT_SOUP:
			case BIRCH_BOAT:
			case BIRCH_SAPLING:
			case BLAZE_POWDER:
			case BLAZE_ROD:
			case BLAZE_SPAWN_EGG:
			case BLUE_ORCHID:
			case BONE:
			case BONE_MEAL:
			case BOOK:
			case BOW:
			case BOWL:
			case BRAIN_CORAL:
			case BRAIN_CORAL_FAN:
			case BRAIN_CORAL_WALL_FAN:
			case BREAD:
			case BRICK:
			case BROWN_MUSHROOM:
			case BUBBLE_COLUMN:
			case BUBBLE_CORAL:
			case BUBBLE_CORAL_FAN:
			case BUBBLE_CORAL_WALL_FAN:
			case BUCKET:
			case CACTUS_GREEN:
			case CARROT:
			case CARROTS:
			case CARROT_ON_A_STICK:
			case CAVE_AIR:
			case CAVE_SPIDER_SPAWN_EGG:
			case CHAINMAIL_BOOTS:
			case CHAINMAIL_CHESTPLATE:
			case CHAINMAIL_HELMET:
			case CHAINMAIL_LEGGINGS:
			case CHARCOAL:
			case CHEST_MINECART:
			case CHICKEN:
			case CHICKEN_SPAWN_EGG:
			case CHORUS_FRUIT:
			case CLAY_BALL:
			case CLOCK:
			case COAL:
			case COCOA_BEANS:
			case COD:
			case COD_BUCKET:
			case COD_SPAWN_EGG:
			case COMMAND_BLOCK_MINECART:
			case COMPARATOR:
			case COMPASS:
			case COOKED_BEEF:
			case COOKED_CHICKEN:
			case COOKED_COD:
			case COOKED_MUTTON:
			case COOKED_PORKCHOP:
			case COOKED_RABBIT:
			case COOKED_SALMON:
			case COOKIE:
			case COW_SPAWN_EGG:
			case CREEPER_SPAWN_EGG:
			case CYAN_DYE:
			case DANDELION:
			case DANDELION_YELLOW:
			case DARK_OAK_BOAT:
			case DARK_OAK_SAPLING:
			case DEAD_BRAIN_CORAL_FAN:
			case DEAD_BRAIN_CORAL_WALL_FAN:
			case DEAD_BUBBLE_CORAL_FAN:
			case DEAD_BUBBLE_CORAL_WALL_FAN:
			case DEAD_BUSH:
			case DEAD_FIRE_CORAL_FAN:
			case DEAD_FIRE_CORAL_WALL_FAN:
			case DEAD_HORN_CORAL_FAN:
			case DEAD_HORN_CORAL_WALL_FAN:
			case DEAD_TUBE_CORAL_FAN:
			case DEAD_TUBE_CORAL_WALL_FAN:
			case DEBUG_STICK:
			case DIAMOND:
			case DIAMOND_AXE:
			case DIAMOND_BOOTS:
			case DIAMOND_CHESTPLATE:
			case DIAMOND_HELMET:
			case DIAMOND_HOE:
			case DIAMOND_HORSE_ARMOR:
			case DIAMOND_LEGGINGS:
			case DIAMOND_PICKAXE:
			case DIAMOND_SHOVEL:
			case DIAMOND_SWORD:
			case DOLPHIN_SPAWN_EGG:
			case DONKEY_SPAWN_EGG:
			case DRAGON_BREATH:
			case DRIED_KELP:
			case DROWNED_SPAWN_EGG:
			case EGG:
			case ELDER_GUARDIAN_SPAWN_EGG:
			case ELYTRA:
			case EMERALD:
			case ENCHANTED_BOOK:
			case ENCHANTED_GOLDEN_APPLE:
			case ENDERMAN_SPAWN_EGG:
			case ENDERMITE_SPAWN_EGG:
			case ENDER_EYE:
			case ENDER_PEARL:
			case END_CRYSTAL:
			case END_ROD:
			case EVOKER_SPAWN_EGG:
			case EXPERIENCE_BOTTLE:
			case FEATHER:
			case FERMENTED_SPIDER_EYE:
			case FERN:
			case FILLED_MAP:
			case FIRE:
			case FIREWORK_ROCKET:
			case FIREWORK_STAR:
			case FIRE_CHARGE:
			case FIRE_CORAL:
			case FIRE_CORAL_FAN:
			case FIRE_CORAL_WALL_FAN:
			case FISHING_ROD:
			case FLINT:
			case FLINT_AND_STEEL:
			case FLOWER_POT:
			case FURNACE_MINECART:
			case GHAST_SPAWN_EGG:
			case GHAST_TEAR:
			case GLASS_BOTTLE:
			case GLISTERING_MELON_SLICE:
			case GLOWSTONE_DUST:
			case GOLDEN_APPLE:
			case GOLDEN_AXE:
			case GOLDEN_BOOTS:
			case GOLDEN_CARROT:
			case GOLDEN_CHESTPLATE:
			case GOLDEN_HELMET:
			case GOLDEN_HOE:
			case GOLDEN_HORSE_ARMOR:
			case GOLDEN_LEGGINGS:
			case GOLDEN_PICKAXE:
			case GOLDEN_SHOVEL:
			case GOLDEN_SWORD:
			case GOLD_INGOT:
			case GOLD_NUGGET:
			case GRASS:
			case GRAY_DYE:
			case GUARDIAN_SPAWN_EGG:
			case GUNPOWDER:
			case HEART_OF_THE_SEA:
			case HOPPER_MINECART:
			case HORN_CORAL:
			case HORN_CORAL_FAN:
			case HORN_CORAL_WALL_FAN:
			case HORSE_SPAWN_EGG:
			case HUSK_SPAWN_EGG:
			case INFESTED_CHISELED_STONE_BRICKS:
			case INFESTED_COBBLESTONE:
			case INFESTED_CRACKED_STONE_BRICKS:
			case INFESTED_MOSSY_STONE_BRICKS:
			case INFESTED_STONE:
			case INFESTED_STONE_BRICKS:
			case INK_SAC:
			case IRON_AXE:
			case IRON_BOOTS:
			case IRON_CHESTPLATE:
			case IRON_HELMET:
			case IRON_HOE:
			case IRON_HORSE_ARMOR:
			case IRON_INGOT:
			case IRON_LEGGINGS:
			case IRON_NUGGET:
			case IRON_PICKAXE:
			case IRON_SHOVEL:
			case IRON_SWORD:
			case ITEM_FRAME:
			case JUNGLE_BOAT:
			case JUNGLE_SAPLING:
			case KELP:
			case KELP_PLANT:
			case KNOWLEDGE_BOOK:
			case LAPIS_LAZULI:
			case LARGE_FERN:
			case LAVA_BUCKET:
			case LEAD:
			case LEATHER:
			case LEATHER_BOOTS:
			case LEATHER_CHESTPLATE:
			case LEATHER_HELMET:
			case LEATHER_LEGGINGS:
			case LIGHT_BLUE_DYE:
			case LIGHT_GRAY_DYE:
			case LILAC:
			case LILY_PAD:
			case LIME_DYE:
			case LINGERING_POTION:
			case LLAMA_SPAWN_EGG:
			case MAGENTA_DYE:
			case MAGMA_CREAM:
			case MAGMA_CUBE_SPAWN_EGG:
			case MAP:
			case MELON_SEEDS:
			case MELON_SLICE:
			case MELON_STEM:
			case MILK_BUCKET:
			case MINECART:
			case MOOSHROOM_SPAWN_EGG:
			case MULE_SPAWN_EGG:
			case MUSHROOM_STEW:
			case MUSIC_DISC_11:
			case MUSIC_DISC_13:
			case MUSIC_DISC_BLOCKS:
			case MUSIC_DISC_CAT:
			case MUSIC_DISC_CHIRP:
			case MUSIC_DISC_FAR:
			case MUSIC_DISC_MALL:
			case MUSIC_DISC_MELLOHI:
			case MUSIC_DISC_STAL:
			case MUSIC_DISC_STRAD:
			case MUSIC_DISC_WAIT:
			case MUSIC_DISC_WARD:
			case MUTTON:
			case NAME_TAG:
			case NAUTILUS_SHELL:
			case NETHER_BRICK:
			case NETHER_STAR:
			case NETHER_WART:
			case OAK_BOAT:
			case OAK_SAPLING:
			case OCELOT_SPAWN_EGG:
			case ORANGE_DYE:
			case ORANGE_TULIP:
			case OXEYE_DAISY:
			case PAINTING:
			case PAPER:
			case PARROT_SPAWN_EGG:
			case PEONY:
			case PHANTOM_MEMBRANE:
			case PHANTOM_SPAWN_EGG:
			case PIG_SPAWN_EGG:
			case PINK_DYE:
			case PINK_TULIP:
			case POISONOUS_POTATO:
			case POLAR_BEAR_SPAWN_EGG:
			case POPPED_CHORUS_FRUIT:
			case POPPY:
			case PORKCHOP:
			case POTATO:
			case POTATOES:
			case POTION:
			case POTTED_ACACIA_SAPLING:
			case POTTED_ALLIUM:
			case POTTED_AZURE_BLUET:
			case POTTED_BIRCH_SAPLING:
			case POTTED_BLUE_ORCHID:
			case POTTED_BROWN_MUSHROOM:
			case POTTED_CACTUS:
			case POTTED_DANDELION:
			case POTTED_DARK_OAK_SAPLING:
			case POTTED_DEAD_BUSH:
			case POTTED_FERN:
			case POTTED_JUNGLE_SAPLING:
			case POTTED_OAK_SAPLING:
			case POTTED_ORANGE_TULIP:
			case POTTED_OXEYE_DAISY:
			case POTTED_PINK_TULIP:
			case POTTED_POPPY:
			case POTTED_RED_MUSHROOM:
			case POTTED_RED_TULIP:
			case POTTED_SPRUCE_SAPLING:
			case POTTED_WHITE_TULIP:
			case PRISMARINE_CRYSTALS:
			case PRISMARINE_SHARD:
			case PUFFERFISH:
			case PUFFERFISH_BUCKET:
			case PUFFERFISH_SPAWN_EGG:
			case PUMPKIN_PIE:
			case PUMPKIN_SEEDS:
			case PUMPKIN_STEM:
			case PURPLE_DYE:
			case QUARTZ:
			case RABBIT:
			case RABBIT_FOOT:
			case RABBIT_HIDE:
			case RABBIT_SPAWN_EGG:
			case RABBIT_STEW:
			case REDSTONE:
			case REDSTONE_TORCH:
			case REDSTONE_WALL_TORCH:
			case REDSTONE_WIRE:
			case RED_MUSHROOM:
			case RED_TULIP:
			case REPEATER:
			case ROSE_BUSH:
			case ROSE_RED:
			case ROTTEN_FLESH:
			case SADDLE:
			case SALMON:
			case SALMON_BUCKET:
			case SALMON_SPAWN_EGG:
			case SCUTE:
			case SEAGRASS:
			case SEA_PICKLE:
			case SHEARS:
			case SHEEP_SPAWN_EGG:
			case SHIELD:
			case SHULKER_SHELL:
			case SHULKER_SPAWN_EGG:
			case SILVERFISH_SPAWN_EGG:
			case SKELETON_HORSE_SPAWN_EGG:
			case SKELETON_SPAWN_EGG:
			case SLIME_BALL:
			case SLIME_BLOCK:
			case SLIME_SPAWN_EGG:
			case SNOWBALL:
			case SPECTRAL_ARROW:
			case SPIDER_EYE:
			case SPIDER_SPAWN_EGG:
			case SPLASH_POTION:
			case SPRUCE_BOAT:
			case SPRUCE_SAPLING:
			case SQUID_SPAWN_EGG:
			case STICK:
			case STONE_AXE:
			case STONE_HOE:
			case STONE_PICKAXE:
			case STONE_SHOVEL:
			case STONE_SWORD:
			case STRAY_SPAWN_EGG:
			case STRING:
			case STRUCTURE_VOID:
			case SUGAR:
			case SUGAR_CANE:
			case SUNFLOWER:
			case TALL_GRASS:
			case TALL_SEAGRASS:
			case TIPPED_ARROW:
			case TNT:
			case TNT_MINECART:
			case TORCH:
			case TOTEM_OF_UNDYING:
			case TRIDENT:
			case TRIPWIRE:
			case TRIPWIRE_HOOK:
			case TROPICAL_FISH:
			case TROPICAL_FISH_BUCKET:
			case TROPICAL_FISH_SPAWN_EGG:
			case TUBE_CORAL:
			case TUBE_CORAL_FAN:
			case TUBE_CORAL_WALL_FAN:
			case TURTLE_HELMET:
			case TURTLE_SPAWN_EGG:
			case VEX_SPAWN_EGG:
			case VILLAGER_SPAWN_EGG:
			case VINDICATOR_SPAWN_EGG:
			case VOID_AIR:
			case WALL_TORCH:
			case WATER_BUCKET:
			case WHEAT:
			case WHEAT_SEEDS:
			case WHITE_TULIP:
			case WITCH_SPAWN_EGG:
			case WITHER_SKELETON_SPAWN_EGG:
			case WOLF_SPAWN_EGG:
			case WOODEN_AXE:
			case WOODEN_HOE:
			case WOODEN_PICKAXE:
			case WOODEN_SHOVEL:
			case WOODEN_SWORD:
			case WRITABLE_BOOK:
			case WRITTEN_BOOK:
			case ZOMBIE_HORSE_SPAWN_EGG:
			case ZOMBIE_PIGMAN_SPAWN_EGG:
			case ZOMBIE_SPAWN_EGG:
			case ZOMBIE_VILLAGER_SPAWN_EGG:
				return 0.0F;
			case BLACK_CARPET:
			case BLUE_CARPET:
			case BROWN_CARPET:
			case CYAN_CARPET:
			case GRAY_CARPET:
			case GREEN_CARPET:
			case LIGHT_BLUE_CARPET:
			case LIGHT_GRAY_CARPET:
			case LIME_CARPET:
			case MAGENTA_CARPET:
			case ORANGE_CARPET:
			case PINK_CARPET:
			case PURPLE_CARPET:
			case RED_CARPET:
			case SNOW:
			case WHITE_CARPET:
			case YELLOW_CARPET:
				return 0.1F;
			case ACACIA_LEAVES:
			case BIRCH_LEAVES:
			case BLACK_BED:
			case BLUE_BED:
			case BROWN_BED:
			case BROWN_MUSHROOM_BLOCK:
			case COCOA:
			case CYAN_BED:
			case DARK_OAK_LEAVES:
			case DAYLIGHT_DETECTOR:
			case GRAY_BED:
			case GREEN_BED:
			case JUNGLE_LEAVES:
			case LIGHT_BLUE_BED:
			case LIGHT_GRAY_BED:
			case LIME_BED:
			case MAGENTA_BED:
			case MUSHROOM_STEM:
			case OAK_LEAVES:
			case ORANGE_BED:
			case PINK_BED:
			case PURPLE_BED:
			case RED_BED:
			case RED_MUSHROOM_BLOCK:
			case SNOW_BLOCK:
			case SPRUCE_LEAVES:
			case VINE:
			case WHITE_BED:
			case YELLOW_BED:
				return 0.2F;
			case BLACK_STAINED_GLASS:
			case BLACK_STAINED_GLASS_PANE:
			case BLUE_STAINED_GLASS:
			case BLUE_STAINED_GLASS_PANE:
			case BROWN_STAINED_GLASS:
			case BROWN_STAINED_GLASS_PANE:
			case CYAN_STAINED_GLASS:
			case CYAN_STAINED_GLASS_PANE:
			case GLASS:
			case GLASS_PANE:
			case GLOWSTONE:
			case GRAY_STAINED_GLASS:
			case GRAY_STAINED_GLASS_PANE:
			case GREEN_STAINED_GLASS:
			case GREEN_STAINED_GLASS_PANE:
			case LIGHT_BLUE_STAINED_GLASS:
			case LIGHT_BLUE_STAINED_GLASS_PANE:
			case LIGHT_GRAY_STAINED_GLASS:
			case LIGHT_GRAY_STAINED_GLASS_PANE:
			case LIME_STAINED_GLASS:
			case LIME_STAINED_GLASS_PANE:
			case MAGENTA_STAINED_GLASS:
			case MAGENTA_STAINED_GLASS_PANE:
			case ORANGE_STAINED_GLASS:
			case ORANGE_STAINED_GLASS_PANE:
			case PINK_STAINED_GLASS:
			case PINK_STAINED_GLASS_PANE:
			case PURPLE_STAINED_GLASS:
			case PURPLE_STAINED_GLASS_PANE:
			case REDSTONE_LAMP:
			case RED_STAINED_GLASS:
			case RED_STAINED_GLASS_PANE:
			case SEA_LANTERN:
			case WHITE_STAINED_GLASS:
			case WHITE_STAINED_GLASS_PANE:
			case YELLOW_STAINED_GLASS:
			case YELLOW_STAINED_GLASS_PANE:
				return 0.3F;
			case CACTUS:
			case CHORUS_FLOWER:
			case CHORUS_PLANT:
			case LADDER:
			case NETHERRACK:
				return 0.4F;
			case ACACIA_BUTTON:
			case ACACIA_PRESSURE_PLATE:
			case BIRCH_BUTTON:
			case BIRCH_PRESSURE_PLATE:
			case BLACK_CONCRETE_POWDER:
			case BLUE_CONCRETE_POWDER:
			case BREWING_STAND:
			case BROWN_CONCRETE_POWDER:
			case CAKE:
			case COARSE_DIRT:
			case CYAN_CONCRETE_POWDER:
			case DARK_OAK_BUTTON:
			case DARK_OAK_PRESSURE_PLATE:
			case DIRT:
			case DRIED_KELP_BLOCK:
			case FROSTED_ICE:
			case GRAY_CONCRETE_POWDER:
			case GREEN_CONCRETE_POWDER:
			case HAY_BLOCK:
			case HEAVY_WEIGHTED_PRESSURE_PLATE:
			case ICE:
			case JUNGLE_BUTTON:
			case JUNGLE_PRESSURE_PLATE:
			case LEVER:
			case LIGHT_BLUE_CONCRETE_POWDER:
			case LIGHT_GRAY_CONCRETE_POWDER:
			case LIGHT_WEIGHTED_PRESSURE_PLATE:
			case LIME_CONCRETE_POWDER:
			case MAGENTA_CONCRETE_POWDER:
			case MAGMA_BLOCK:
			case OAK_BUTTON:
			case OAK_PRESSURE_PLATE:
			case ORANGE_CONCRETE_POWDER:
			case PACKED_ICE:
			case PINK_CONCRETE_POWDER:
			case PISTON:
			case PISTON_HEAD:
			case PODZOL:
			case PURPLE_CONCRETE_POWDER:
			case RED_CONCRETE_POWDER:
			case RED_SAND:
			case SAND:
			case SOUL_SAND:
			case SPRUCE_BUTTON:
			case SPRUCE_PRESSURE_PLATE:
			case STICKY_PISTON:
			case STONE_BUTTON:
			case STONE_PRESSURE_PLATE:
			case TURTLE_EGG:
			case WHITE_CONCRETE_POWDER:
			case YELLOW_CONCRETE_POWDER:
				return 0.5F;
			case CLAY:
			case FARMLAND:
			case GRASS_BLOCK:
			case GRAVEL:
			case MYCELIUM:
			case SPONGE:
			case WET_SPONGE:
				return 0.6F;
			case GRASS_PATH:
				return 0.65F;
			case ACTIVATOR_RAIL:
			case DETECTOR_RAIL:
			case POWERED_RAIL:
			case RAIL:
				return 0.7F;
			case BLACK_WOOL:
			case BLUE_WOOL:
			case BROWN_WOOL:
			case CHISELED_QUARTZ_BLOCK:
			case CHISELED_RED_SANDSTONE:
			case CHISELED_SANDSTONE:
			case CUT_RED_SANDSTONE:
			case CUT_SANDSTONE:
			case CYAN_WOOL:
			case END_STONE_BRICKS:
			case GRAY_WOOL:
			case GREEN_WOOL:
			case LIGHT_BLUE_WOOL:
			case LIGHT_GRAY_WOOL:
			case LIME_WOOL:
			case MAGENTA_WOOL:
			case NOTE_BLOCK:
			case ORANGE_WOOL:
			case PINK_WOOL:
			case PURPLE_WOOL:
			case QUARTZ_BLOCK:
			case QUARTZ_PILLAR:
			case QUARTZ_STAIRS:
			case RED_SANDSTONE:
			case RED_SANDSTONE_STAIRS:
			case RED_WOOL:
			case SANDSTONE:
			case SANDSTONE_STAIRS:
			case WHITE_WOOL:
			case YELLOW_WOOL:
				return 0.8F;
			case BLACK_BANNER:
			case BLACK_WALL_BANNER:
			case BLUE_BANNER:
			case BLUE_WALL_BANNER:
			case BROWN_BANNER:
			case BROWN_WALL_BANNER:
			case CARVED_PUMPKIN:
			case CREEPER_HEAD:
			case CREEPER_WALL_HEAD:
			case CYAN_BANNER:
			case CYAN_WALL_BANNER:
			case DRAGON_HEAD:
			case DRAGON_WALL_HEAD:
			case GRAY_BANNER:
			case GRAY_WALL_BANNER:
			case GREEN_BANNER:
			case GREEN_WALL_BANNER:
			case JACK_O_LANTERN:
			case LIGHT_BLUE_BANNER:
			case LIGHT_BLUE_WALL_BANNER:
			case LIGHT_GRAY_BANNER:
			case LIGHT_GRAY_WALL_BANNER:
			case LIME_BANNER:
			case LIME_WALL_BANNER:
			case MAGENTA_BANNER:
			case MAGENTA_WALL_BANNER:
			case MELON:
			case NETHER_WART_BLOCK:
			case ORANGE_BANNER:
			case ORANGE_WALL_BANNER:
			case PINK_BANNER:
			case PINK_WALL_BANNER:
			case PLAYER_HEAD:
			case PLAYER_WALL_HEAD:
			case PUMPKIN:
			case PURPLE_BANNER:
			case PURPLE_WALL_BANNER:
			case RED_BANNER:
			case RED_WALL_BANNER:
			case SIGN:
			case SKELETON_SKULL:
			case SKELETON_WALL_SKULL:
			case WALL_SIGN:
			case WHITE_BANNER:
			case WHITE_WALL_BANNER:
			case WITHER_SKELETON_SKULL:
			case WITHER_SKELETON_WALL_SKULL:
			case YELLOW_BANNER:
			case YELLOW_WALL_BANNER:
			case ZOMBIE_HEAD:
			case ZOMBIE_WALL_HEAD:
				return 1.0F;
			case BLACK_TERRACOTTA:
			case BLUE_TERRACOTTA:
			case BROWN_TERRACOTTA:
			case CYAN_TERRACOTTA:
			case GRAY_TERRACOTTA:
			case GREEN_TERRACOTTA:
			case LIGHT_BLUE_TERRACOTTA:
			case LIGHT_GRAY_TERRACOTTA:
			case LIME_TERRACOTTA:
			case MAGENTA_TERRACOTTA:
			case ORANGE_TERRACOTTA:
			case PINK_TERRACOTTA:
			case PURPLE_TERRACOTTA:
			case RED_TERRACOTTA:
			case TERRACOTTA:
			case WHITE_TERRACOTTA:
			case YELLOW_TERRACOTTA:
				return 1.25F;
			case BLACK_GLAZED_TERRACOTTA:
			case BLUE_GLAZED_TERRACOTTA:
			case BROWN_GLAZED_TERRACOTTA:
			case CYAN_GLAZED_TERRACOTTA:
			case GRAY_GLAZED_TERRACOTTA:
			case GREEN_GLAZED_TERRACOTTA:
			case LIGHT_BLUE_GLAZED_TERRACOTTA:
			case LIGHT_GRAY_GLAZED_TERRACOTTA:
			case LIME_GLAZED_TERRACOTTA:
			case MAGENTA_GLAZED_TERRACOTTA:
			case ORANGE_GLAZED_TERRACOTTA:
			case PINK_GLAZED_TERRACOTTA:
			case PURPLE_GLAZED_TERRACOTTA:
			case RED_GLAZED_TERRACOTTA:
			case WHITE_GLAZED_TERRACOTTA:
			case YELLOW_GLAZED_TERRACOTTA:
				return 1.4F;
			case ANDESITE:
			case BOOKSHELF:
			case BRAIN_CORAL_BLOCK:
			case BUBBLE_CORAL_BLOCK:
			case CHISELED_STONE_BRICKS:
			case CRACKED_STONE_BRICKS:
			case DARK_PRISMARINE:
			case DARK_PRISMARINE_SLAB:
			case DARK_PRISMARINE_STAIRS:
			case DEAD_BRAIN_CORAL_BLOCK:
			case DEAD_BUBBLE_CORAL_BLOCK:
			case DEAD_FIRE_CORAL_BLOCK:
			case DEAD_HORN_CORAL_BLOCK:
			case DEAD_TUBE_CORAL_BLOCK:
			case DIORITE:
			case FIRE_CORAL_BLOCK:
			case GRANITE:
			case HORN_CORAL_BLOCK:
			case MOSSY_STONE_BRICKS:
			case POLISHED_ANDESITE:
			case POLISHED_DIORITE:
			case POLISHED_GRANITE:
			case PRISMARINE:
			case PRISMARINE_BRICKS:
			case PRISMARINE_BRICK_SLAB:
			case PRISMARINE_BRICK_STAIRS:
			case PRISMARINE_SLAB:
			case PRISMARINE_STAIRS:
			case PURPUR_BLOCK:
			case PURPUR_PILLAR:
			case PURPUR_STAIRS:
			case STONE:
			case STONE_BRICKS:
			case STONE_BRICK_STAIRS:
			case TUBE_CORAL_BLOCK:
				return 1.5F;
			case BLACK_CONCRETE:
			case BLUE_CONCRETE:
			case BROWN_CONCRETE:
			case CYAN_CONCRETE:
			case GRAY_CONCRETE:
			case GREEN_CONCRETE:
			case LIGHT_BLUE_CONCRETE:
			case LIGHT_GRAY_CONCRETE:
			case LIME_CONCRETE:
			case MAGENTA_CONCRETE:
			case ORANGE_CONCRETE:
			case PINK_CONCRETE:
			case PURPLE_CONCRETE:
			case RED_CONCRETE:
			case WHITE_CONCRETE:
			case YELLOW_CONCRETE:
				return 1.8F;
			case ACACIA_FENCE:
			case ACACIA_FENCE_GATE:
			case ACACIA_LOG:
			case ACACIA_PLANKS:
			case ACACIA_SLAB:
			case ACACIA_STAIRS:
			case ACACIA_WOOD:
			case BIRCH_FENCE:
			case BIRCH_FENCE_GATE:
			case BIRCH_LOG:
			case BIRCH_PLANKS:
			case BIRCH_SLAB:
			case BIRCH_STAIRS:
			case BIRCH_WOOD:
			case BLACK_SHULKER_BOX:
			case BLUE_SHULKER_BOX:
			case BONE_BLOCK:
			case BRICKS:
			case BRICK_SLAB:
			case BRICK_STAIRS:
			case BROWN_SHULKER_BOX:
			case CAULDRON:
			case COBBLESTONE:
			case COBBLESTONE_SLAB:
			case COBBLESTONE_STAIRS:
			case COBBLESTONE_WALL:
			case CYAN_SHULKER_BOX:
			case DARK_OAK_FENCE:
			case DARK_OAK_FENCE_GATE:
			case DARK_OAK_LOG:
			case DARK_OAK_PLANKS:
			case DARK_OAK_SLAB:
			case DARK_OAK_STAIRS:
			case DARK_OAK_WOOD:
			case GRAY_SHULKER_BOX:
			case GREEN_SHULKER_BOX:
			case JUKEBOX:
			case JUNGLE_FENCE:
			case JUNGLE_FENCE_GATE:
			case JUNGLE_LOG:
			case JUNGLE_PLANKS:
			case JUNGLE_SLAB:
			case JUNGLE_STAIRS:
			case JUNGLE_WOOD:
			case LIGHT_BLUE_SHULKER_BOX:
			case LIGHT_GRAY_SHULKER_BOX:
			case LIME_SHULKER_BOX:
			case MAGENTA_SHULKER_BOX:
			case MOSSY_COBBLESTONE:
			case MOSSY_COBBLESTONE_WALL:
			case NETHER_BRICKS:
			case NETHER_BRICK_FENCE:
			case NETHER_BRICK_SLAB:
			case NETHER_BRICK_STAIRS:
			case OAK_FENCE:
			case OAK_FENCE_GATE:
			case OAK_LOG:
			case OAK_PLANKS:
			case OAK_SLAB:
			case OAK_STAIRS:
			case OAK_WOOD:
			case ORANGE_SHULKER_BOX:
			case PETRIFIED_OAK_SLAB:
			case PINK_SHULKER_BOX:
			case PURPLE_SHULKER_BOX:
			case PURPUR_SLAB:
			case QUARTZ_SLAB:
			case RED_NETHER_BRICKS:
			case RED_SANDSTONE_SLAB:
			case RED_SHULKER_BOX:
			case SANDSTONE_SLAB:
			case SHULKER_BOX:
			case SMOOTH_QUARTZ:
			case SMOOTH_RED_SANDSTONE:
			case SMOOTH_SANDSTONE:
			case SMOOTH_STONE:
			case SPRUCE_FENCE:
			case SPRUCE_FENCE_GATE:
			case SPRUCE_LOG:
			case SPRUCE_PLANKS:
			case SPRUCE_SLAB:
			case SPRUCE_STAIRS:
			case SPRUCE_WOOD:
			case STONE_BRICK_SLAB:
			case STONE_SLAB:
			case STRIPPED_ACACIA_LOG:
			case STRIPPED_ACACIA_WOOD:
			case STRIPPED_BIRCH_LOG:
			case STRIPPED_BIRCH_WOOD:
			case STRIPPED_DARK_OAK_LOG:
			case STRIPPED_DARK_OAK_WOOD:
			case STRIPPED_JUNGLE_LOG:
			case STRIPPED_JUNGLE_WOOD:
			case STRIPPED_OAK_LOG:
			case STRIPPED_OAK_WOOD:
			case STRIPPED_SPRUCE_LOG:
			case STRIPPED_SPRUCE_WOOD:
			case WHITE_SHULKER_BOX:
			case YELLOW_SHULKER_BOX:
				return 2.0F;
			case CHEST:
			case CRAFTING_TABLE:
			case TRAPPED_CHEST:
				return 2.5F;
			case BLUE_ICE:
				return 2.8F;
			case ACACIA_DOOR:
			case ACACIA_TRAPDOOR:
			case BEACON:
			case BIRCH_DOOR:
			case BIRCH_TRAPDOOR:
			case COAL_ORE:
			case CONDUIT:
			case DARK_OAK_DOOR:
			case DARK_OAK_TRAPDOOR:
			case DIAMOND_ORE:
			case DRAGON_EGG:
			case EMERALD_ORE:
			case END_STONE:
			case GOLD_BLOCK:
			case GOLD_ORE:
			case HOPPER:
			case IRON_ORE:
			case JUNGLE_DOOR:
			case JUNGLE_TRAPDOOR:
			case LAPIS_BLOCK:
			case LAPIS_ORE:
			case NETHER_QUARTZ_ORE:
			case OAK_DOOR:
			case OAK_TRAPDOOR:
			case OBSERVER:
			case REDSTONE_ORE:
			case SPRUCE_DOOR:
			case SPRUCE_TRAPDOOR:
				return 3.0F;
			case DISPENSER:
			case DROPPER:
			case FURNACE:
				return 3.5F;
			case COBWEB:
				return 4.0F;
			case ANVIL:
			case CHIPPED_ANVIL:
			case COAL_BLOCK:
			case DAMAGED_ANVIL:
			case DIAMOND_BLOCK:
			case EMERALD_BLOCK:
			case ENCHANTING_TABLE:
			case IRON_BARS:
			case IRON_BLOCK:
			case IRON_DOOR:
			case IRON_TRAPDOOR:
			case REDSTONE_BLOCK:
			case SPAWNER:
				return 5.0F;
			case ENDER_CHEST:
				return 22.5F;
			case OBSIDIAN:
				return 50.0F;
			case LAVA:
			case WATER:
				return 100.0F;
			// --- Legacy Seperator ---
			case LEGACY_BEDROCK:
			case LEGACY_PISTON_MOVING_PIECE:
			case LEGACY_PORTAL:
			case LEGACY_ENDER_PORTAL:
			case LEGACY_ENDER_PORTAL_FRAME:
			case LEGACY_COMMAND:
			case LEGACY_BARRIER:
			case LEGACY_END_GATEWAY:
			case LEGACY_COMMAND_REPEATING:
			case LEGACY_COMMAND_CHAIN:
			case LEGACY_STRUCTURE_BLOCK:
				return -1.0F;
			case LEGACY_AIR:
			case LEGACY_SAPLING:
			case LEGACY_LONG_GRASS:
			case LEGACY_DEAD_BUSH:
			case LEGACY_YELLOW_FLOWER:
			case LEGACY_RED_ROSE:
			case LEGACY_BROWN_MUSHROOM:
			case LEGACY_RED_MUSHROOM:
			case LEGACY_TNT:
			case LEGACY_TORCH:
			case LEGACY_FIRE:
			case LEGACY_REDSTONE_WIRE:
			case LEGACY_CROPS:
			case LEGACY_BURNING_FURNACE:
			case LEGACY_WALL_SIGN:
			case LEGACY_REDSTONE_TORCH_OFF:
			case LEGACY_REDSTONE_TORCH_ON:
			case LEGACY_SUGAR_CANE_BLOCK:
			case LEGACY_DIODE_BLOCK_OFF:
			case LEGACY_DIODE_BLOCK_ON:
			case LEGACY_MONSTER_EGGS:
			case LEGACY_PUMPKIN_STEM:
			case LEGACY_MELON_STEM:
			case LEGACY_WATER_LILY:
			case LEGACY_NETHER_WARTS:
			case LEGACY_TRIPWIRE_HOOK:
			case LEGACY_TRIPWIRE:
			case LEGACY_FLOWER_POT:
			case LEGACY_CARROT:
			case LEGACY_POTATO:
			case LEGACY_SKULL:
			case LEGACY_REDSTONE_COMPARATOR_OFF:
			case LEGACY_REDSTONE_COMPARATOR_ON:
			case LEGACY_SLIME_BLOCK:
			case LEGACY_DOUBLE_PLANT:
			case LEGACY_WALL_BANNER:
			case LEGACY_END_ROD:
			case LEGACY_BEETROOT_BLOCK:
			case LEGACY_STRUCTURE_VOID:
			case LEGACY_IRON_SPADE:
			case LEGACY_IRON_PICKAXE:
			case LEGACY_IRON_AXE:
			case LEGACY_FLINT_AND_STEEL:
			case LEGACY_APPLE:
			case LEGACY_BOW:
			case LEGACY_ARROW:
			case LEGACY_COAL:
			case LEGACY_DIAMOND:
			case LEGACY_IRON_INGOT:
			case LEGACY_GOLD_INGOT:
			case LEGACY_IRON_SWORD:
			case LEGACY_WOOD_SWORD:
			case LEGACY_WOOD_SPADE:
			case LEGACY_WOOD_PICKAXE:
			case LEGACY_WOOD_AXE:
			case LEGACY_STONE_SWORD:
			case LEGACY_STONE_SPADE:
			case LEGACY_STONE_PICKAXE:
			case LEGACY_STONE_AXE:
			case LEGACY_DIAMOND_SWORD:
			case LEGACY_DIAMOND_SPADE:
			case LEGACY_DIAMOND_PICKAXE:
			case LEGACY_DIAMOND_AXE:
			case LEGACY_STICK:
			case LEGACY_BOWL:
			case LEGACY_MUSHROOM_SOUP:
			case LEGACY_GOLD_SWORD:
			case LEGACY_GOLD_SPADE:
			case LEGACY_GOLD_PICKAXE:
			case LEGACY_GOLD_AXE:
			case LEGACY_STRING:
			case LEGACY_FEATHER:
			case LEGACY_SULPHUR:
			case LEGACY_WOOD_HOE:
			case LEGACY_STONE_HOE:
			case LEGACY_IRON_HOE:
			case LEGACY_DIAMOND_HOE:
			case LEGACY_GOLD_HOE:
			case LEGACY_SEEDS:
			case LEGACY_WHEAT:
			case LEGACY_BREAD:
			case LEGACY_LEATHER_HELMET:
			case LEGACY_LEATHER_CHESTPLATE:
			case LEGACY_LEATHER_LEGGINGS:
			case LEGACY_LEATHER_BOOTS:
			case LEGACY_CHAINMAIL_HELMET:
			case LEGACY_CHAINMAIL_CHESTPLATE:
			case LEGACY_CHAINMAIL_LEGGINGS:
			case LEGACY_CHAINMAIL_BOOTS:
			case LEGACY_IRON_HELMET:
			case LEGACY_IRON_CHESTPLATE:
			case LEGACY_IRON_LEGGINGS:
			case LEGACY_IRON_BOOTS:
			case LEGACY_DIAMOND_HELMET:
			case LEGACY_DIAMOND_CHESTPLATE:
			case LEGACY_DIAMOND_LEGGINGS:
			case LEGACY_DIAMOND_BOOTS:
			case LEGACY_GOLD_HELMET:
			case LEGACY_GOLD_CHESTPLATE:
			case LEGACY_GOLD_LEGGINGS:
			case LEGACY_GOLD_BOOTS:
			case LEGACY_FLINT:
			case LEGACY_PORK:
			case LEGACY_GRILLED_PORK:
			case LEGACY_PAINTING:
			case LEGACY_GOLDEN_APPLE:
			case LEGACY_BUCKET:
			case LEGACY_WATER_BUCKET:
			case LEGACY_LAVA_BUCKET:
			case LEGACY_MINECART:
			case LEGACY_SADDLE:
			case LEGACY_REDSTONE:
			case LEGACY_SNOW_BALL:
			case LEGACY_BOAT:
			case LEGACY_LEATHER:
			case LEGACY_MILK_BUCKET:
			case LEGACY_CLAY_BRICK:
			case LEGACY_CLAY_BALL:
			case LEGACY_SUGAR_CANE:
			case LEGACY_PAPER:
			case LEGACY_BOOK:
			case LEGACY_SLIME_BALL:
			case LEGACY_STORAGE_MINECART:
			case LEGACY_POWERED_MINECART:
			case LEGACY_EGG:
			case LEGACY_COMPASS:
			case LEGACY_FISHING_ROD:
			case LEGACY_WATCH:
			case LEGACY_GLOWSTONE_DUST:
			case LEGACY_RAW_FISH:
			case LEGACY_COOKED_FISH:
			case LEGACY_INK_SACK:
			case LEGACY_BONE:
			case LEGACY_SUGAR:
			case LEGACY_DIODE:
			case LEGACY_COOKIE:
			case LEGACY_MAP:
			case LEGACY_SHEARS:
			case LEGACY_MELON:
			case LEGACY_PUMPKIN_SEEDS:
			case LEGACY_MELON_SEEDS:
			case LEGACY_RAW_BEEF:
			case LEGACY_COOKED_BEEF:
			case LEGACY_RAW_CHICKEN:
			case LEGACY_COOKED_CHICKEN:
			case LEGACY_ROTTEN_FLESH:
			case LEGACY_ENDER_PEARL:
			case LEGACY_BLAZE_ROD:
			case LEGACY_GHAST_TEAR:
			case LEGACY_GOLD_NUGGET:
			case LEGACY_NETHER_STALK:
			case LEGACY_POTION:
			case LEGACY_GLASS_BOTTLE:
			case LEGACY_SPIDER_EYE:
			case LEGACY_FERMENTED_SPIDER_EYE:
			case LEGACY_BLAZE_POWDER:
			case LEGACY_MAGMA_CREAM:
			case LEGACY_EYE_OF_ENDER:
			case LEGACY_SPECKLED_MELON:
			case LEGACY_MONSTER_EGG:
			case LEGACY_EXP_BOTTLE:
			case LEGACY_FIREBALL:
			case LEGACY_BOOK_AND_QUILL:
			case LEGACY_WRITTEN_BOOK:
			case LEGACY_EMERALD:
			case LEGACY_ITEM_FRAME:
			case LEGACY_FLOWER_POT_ITEM:
			case LEGACY_CARROT_ITEM:
			case LEGACY_POTATO_ITEM:
			case LEGACY_BAKED_POTATO:
			case LEGACY_POISONOUS_POTATO:
			case LEGACY_EMPTY_MAP:
			case LEGACY_GOLDEN_CARROT:
			case LEGACY_CARROT_STICK:
			case LEGACY_NETHER_STAR:
			case LEGACY_PUMPKIN_PIE:
			case LEGACY_FIREWORK:
			case LEGACY_FIREWORK_CHARGE:
			case LEGACY_ENCHANTED_BOOK:
			case LEGACY_REDSTONE_COMPARATOR:
			case LEGACY_NETHER_BRICK_ITEM:
			case LEGACY_QUARTZ:
			case LEGACY_EXPLOSIVE_MINECART:
			case LEGACY_HOPPER_MINECART:
			case LEGACY_PRISMARINE_SHARD:
			case LEGACY_PRISMARINE_CRYSTALS:
			case LEGACY_RABBIT:
			case LEGACY_COOKED_RABBIT:
			case LEGACY_RABBIT_STEW:
			case LEGACY_RABBIT_FOOT:
			case LEGACY_RABBIT_HIDE:
			case LEGACY_ARMOR_STAND:
			case LEGACY_IRON_BARDING:
			case LEGACY_GOLD_BARDING:
			case LEGACY_DIAMOND_BARDING:
			case LEGACY_LEASH:
			case LEGACY_NAME_TAG:
			case LEGACY_COMMAND_MINECART:
			case LEGACY_MUTTON:
			case LEGACY_COOKED_MUTTON:
			case LEGACY_END_CRYSTAL:
			case LEGACY_CHORUS_FRUIT:
			case LEGACY_CHORUS_FRUIT_POPPED:
			case LEGACY_BEETROOT:
			case LEGACY_BEETROOT_SEEDS:
			case LEGACY_BEETROOT_SOUP:
			case LEGACY_DRAGONS_BREATH:
			case LEGACY_SPLASH_POTION:
			case LEGACY_SPECTRAL_ARROW:
			case LEGACY_TIPPED_ARROW:
			case LEGACY_LINGERING_POTION:
			case LEGACY_SHIELD:
			case LEGACY_ELYTRA:
			case LEGACY_BOAT_SPRUCE:
			case LEGACY_BOAT_BIRCH:
			case LEGACY_BOAT_JUNGLE:
			case LEGACY_BOAT_ACACIA:
			case LEGACY_BOAT_DARK_OAK:
			case LEGACY_TOTEM:
			case LEGACY_SHULKER_SHELL:
			case LEGACY_IRON_NUGGET:
			case LEGACY_KNOWLEDGE_BOOK:
			case LEGACY_GOLD_RECORD:
			case LEGACY_GREEN_RECORD:
			case LEGACY_RECORD_3:
			case LEGACY_RECORD_4:
			case LEGACY_RECORD_5:
			case LEGACY_RECORD_6:
			case LEGACY_RECORD_7:
			case LEGACY_RECORD_8:
			case LEGACY_RECORD_9:
			case LEGACY_RECORD_10:
			case LEGACY_RECORD_11:
			case LEGACY_RECORD_12:
				return 0.0F;
			case LEGACY_SNOW:
			case LEGACY_CARPET:
				return 0.1F;
			case LEGACY_LEAVES:
			case LEGACY_BED_BLOCK:
			case LEGACY_SNOW_BLOCK:
			case LEGACY_HUGE_MUSHROOM_1:
			case LEGACY_HUGE_MUSHROOM_2:
			case LEGACY_VINE:
			case LEGACY_COCOA:
			case LEGACY_DAYLIGHT_DETECTOR:
			case LEGACY_LEAVES_2:
			case LEGACY_DAYLIGHT_DETECTOR_INVERTED:
			case LEGACY_BED:
				return 0.2F;
			case LEGACY_GLASS:
			case LEGACY_GLOWSTONE:
			case LEGACY_STAINED_GLASS:
			case LEGACY_THIN_GLASS:
			case LEGACY_REDSTONE_LAMP_OFF:
			case LEGACY_REDSTONE_LAMP_ON:
			case LEGACY_STAINED_GLASS_PANE:
			case LEGACY_SEA_LANTERN:
				return 0.3F;
			case LEGACY_LADDER:
			case LEGACY_CACTUS:
			case LEGACY_NETHERRACK:
			case LEGACY_CHORUS_PLANT:
			case LEGACY_CHORUS_FLOWER:
				return 0.4F;
			case LEGACY_DIRT:
			case LEGACY_SAND:
			case LEGACY_PISTON_STICKY_BASE:
			case LEGACY_PISTON_BASE:
			case LEGACY_PISTON_EXTENSION:
			case LEGACY_LEVER:
			case LEGACY_STONE_PLATE:
			case LEGACY_WOOD_PLATE:
			case LEGACY_STONE_BUTTON:
			case LEGACY_ICE:
			case LEGACY_SOUL_SAND:
			case LEGACY_CAKE_BLOCK:
			case LEGACY_BREWING_STAND:
			case LEGACY_WOOD_BUTTON:
			case LEGACY_GOLD_PLATE:
			case LEGACY_IRON_PLATE:
			case LEGACY_HAY_BLOCK:
			case LEGACY_PACKED_ICE:
			case LEGACY_FROSTED_ICE:
			case LEGACY_MAGMA:
			case LEGACY_CONCRETE_POWDER:
			case LEGACY_CAKE:
			case LEGACY_BREWING_STAND_ITEM:
				return 0.5F;
			case LEGACY_GRASS:
			case LEGACY_GRAVEL:
			case LEGACY_SPONGE:
			case LEGACY_SOIL:
			case LEGACY_CLAY:
			case LEGACY_MYCEL:
				return 0.6F;
			case LEGACY_GRASS_PATH:
				return 0.65F;
			case LEGACY_POWERED_RAIL:
			case LEGACY_DETECTOR_RAIL:
			case LEGACY_RAILS:
			case LEGACY_ACTIVATOR_RAIL:
				return 0.7F;
			case LEGACY_SANDSTONE:
			case LEGACY_NOTE_BLOCK:
			case LEGACY_WOOL:
			case LEGACY_SANDSTONE_STAIRS:
			case LEGACY_QUARTZ_BLOCK:
			case LEGACY_QUARTZ_STAIRS:
			case LEGACY_RED_SANDSTONE:
			case LEGACY_RED_SANDSTONE_STAIRS:
			case LEGACY_END_BRICKS:
				return 0.8F;
			case LEGACY_SIGN_POST:
			case LEGACY_PUMPKIN:
			case LEGACY_JACK_O_LANTERN:
			case LEGACY_MELON_BLOCK:
			case LEGACY_STANDING_BANNER:
			case LEGACY_NETHER_WART_BLOCK:
			case LEGACY_SIGN:
			case LEGACY_SKULL_ITEM:
			case LEGACY_BANNER:
				return 1.0F;
			case LEGACY_STAINED_CLAY:
			case LEGACY_HARD_CLAY:
				return 1.25F;
			case LEGACY_WHITE_GLAZED_TERRACOTTA:
			case LEGACY_ORANGE_GLAZED_TERRACOTTA:
			case LEGACY_MAGENTA_GLAZED_TERRACOTTA:
			case LEGACY_LIGHT_BLUE_GLAZED_TERRACOTTA:
			case LEGACY_YELLOW_GLAZED_TERRACOTTA:
			case LEGACY_LIME_GLAZED_TERRACOTTA:
			case LEGACY_PINK_GLAZED_TERRACOTTA:
			case LEGACY_GRAY_GLAZED_TERRACOTTA:
			case LEGACY_SILVER_GLAZED_TERRACOTTA:
			case LEGACY_CYAN_GLAZED_TERRACOTTA:
			case LEGACY_PURPLE_GLAZED_TERRACOTTA:
			case LEGACY_BLUE_GLAZED_TERRACOTTA:
			case LEGACY_BROWN_GLAZED_TERRACOTTA:
			case LEGACY_GREEN_GLAZED_TERRACOTTA:
			case LEGACY_RED_GLAZED_TERRACOTTA:
			case LEGACY_BLACK_GLAZED_TERRACOTTA:
				return 1.4F;
			case LEGACY_STONE:
			case LEGACY_BOOKSHELF:
			case LEGACY_SMOOTH_BRICK:
			case LEGACY_SMOOTH_STAIRS:
			case LEGACY_PRISMARINE:
			case LEGACY_PURPUR_BLOCK:
			case LEGACY_PURPUR_PILLAR:
			case LEGACY_PURPUR_STAIRS:
				return 1.5F;
			case LEGACY_CONCRETE:
				return 1.8F;
			case LEGACY_COBBLESTONE:
			case LEGACY_WOOD:
			case LEGACY_LOG:
			case LEGACY_DOUBLE_STEP:
			case LEGACY_STEP:
			case LEGACY_BRICK:
			case LEGACY_MOSSY_COBBLESTONE:
			case LEGACY_WOOD_STAIRS:
			case LEGACY_COBBLESTONE_STAIRS:
			case LEGACY_JUKEBOX:
			case LEGACY_FENCE:
			case LEGACY_FENCE_GATE:
			case LEGACY_BRICK_STAIRS:
			case LEGACY_NETHER_BRICK:
			case LEGACY_NETHER_FENCE:
			case LEGACY_NETHER_BRICK_STAIRS:
			case LEGACY_CAULDRON:
			case LEGACY_WOOD_DOUBLE_STEP:
			case LEGACY_WOOD_STEP:
			case LEGACY_SPRUCE_WOOD_STAIRS:
			case LEGACY_BIRCH_WOOD_STAIRS:
			case LEGACY_JUNGLE_WOOD_STAIRS:
			case LEGACY_COBBLE_WALL:
			case LEGACY_LOG_2:
			case LEGACY_ACACIA_STAIRS:
			case LEGACY_DARK_OAK_STAIRS:
			case LEGACY_DOUBLE_STONE_SLAB2:
			case LEGACY_STONE_SLAB2:
			case LEGACY_SPRUCE_FENCE_GATE:
			case LEGACY_BIRCH_FENCE_GATE:
			case LEGACY_JUNGLE_FENCE_GATE:
			case LEGACY_DARK_OAK_FENCE_GATE:
			case LEGACY_ACACIA_FENCE_GATE:
			case LEGACY_SPRUCE_FENCE:
			case LEGACY_BIRCH_FENCE:
			case LEGACY_JUNGLE_FENCE:
			case LEGACY_DARK_OAK_FENCE:
			case LEGACY_ACACIA_FENCE:
			case LEGACY_PURPUR_DOUBLE_SLAB:
			case LEGACY_PURPUR_SLAB:
			case LEGACY_RED_NETHER_BRICK:
			case LEGACY_BONE_BLOCK:
			case LEGACY_WHITE_SHULKER_BOX:
			case LEGACY_ORANGE_SHULKER_BOX:
			case LEGACY_MAGENTA_SHULKER_BOX:
			case LEGACY_LIGHT_BLUE_SHULKER_BOX:
			case LEGACY_YELLOW_SHULKER_BOX:
			case LEGACY_LIME_SHULKER_BOX:
			case LEGACY_PINK_SHULKER_BOX:
			case LEGACY_GRAY_SHULKER_BOX:
			case LEGACY_SILVER_SHULKER_BOX:
			case LEGACY_CYAN_SHULKER_BOX:
			case LEGACY_PURPLE_SHULKER_BOX:
			case LEGACY_BLUE_SHULKER_BOX:
			case LEGACY_BROWN_SHULKER_BOX:
			case LEGACY_GREEN_SHULKER_BOX:
			case LEGACY_RED_SHULKER_BOX:
			case LEGACY_BLACK_SHULKER_BOX:
			case LEGACY_CAULDRON_ITEM:
				return 2.0F;
			case LEGACY_CHEST:
			case LEGACY_WORKBENCH:
			case LEGACY_TRAPPED_CHEST:
				return 2.5F;
			case LEGACY_GOLD_ORE:
			case LEGACY_IRON_ORE:
			case LEGACY_COAL_ORE:
			case LEGACY_LAPIS_ORE:
			case LEGACY_LAPIS_BLOCK:
			case LEGACY_GOLD_BLOCK:
			case LEGACY_DIAMOND_ORE:
			case LEGACY_WOODEN_DOOR:
			case LEGACY_REDSTONE_ORE:
			case LEGACY_GLOWING_REDSTONE_ORE:
			case LEGACY_TRAP_DOOR:
			case LEGACY_ENDER_STONE:
			case LEGACY_DRAGON_EGG:
			case LEGACY_EMERALD_ORE:
			case LEGACY_BEACON:
			case LEGACY_QUARTZ_ORE:
			case LEGACY_HOPPER:
			case LEGACY_SPRUCE_DOOR:
			case LEGACY_BIRCH_DOOR:
			case LEGACY_JUNGLE_DOOR:
			case LEGACY_ACACIA_DOOR:
			case LEGACY_DARK_OAK_DOOR:
			case LEGACY_OBSERVER:
			case LEGACY_WOOD_DOOR:
			case LEGACY_SPRUCE_DOOR_ITEM:
			case LEGACY_BIRCH_DOOR_ITEM:
			case LEGACY_JUNGLE_DOOR_ITEM:
			case LEGACY_ACACIA_DOOR_ITEM:
			case LEGACY_DARK_OAK_DOOR_ITEM:
				return 3.0F;
			case LEGACY_DISPENSER:
			case LEGACY_FURNACE:
			case LEGACY_DROPPER:
				return 3.5F;
			case LEGACY_WEB:
				return 4.0F;
			case LEGACY_IRON_BLOCK:
			case LEGACY_MOB_SPAWNER:
			case LEGACY_DIAMOND_BLOCK:
			case LEGACY_IRON_DOOR_BLOCK:
			case LEGACY_IRON_FENCE:
			case LEGACY_ENCHANTMENT_TABLE:
			case LEGACY_EMERALD_BLOCK:
			case LEGACY_ANVIL:
			case LEGACY_REDSTONE_BLOCK:
			case LEGACY_IRON_TRAPDOOR:
			case LEGACY_COAL_BLOCK:
			case LEGACY_IRON_DOOR:
				return 5.0F;
			case LEGACY_ENDER_CHEST:
				return 22.5F;
			case LEGACY_OBSIDIAN:
				return 50.0F;
			case LEGACY_WATER:
			case LEGACY_STATIONARY_WATER:
			case LEGACY_LAVA:
			case LEGACY_STATIONARY_LAVA:
				return 100.0F;
			default:
				return 0F;
			// </editor-fold>
			}
		}
	}

	/**
	 * Obtains the blast resistance value (also known as block "durability"). This
	 * value is used in explosions to calculate whether a block should be broken or
	 * not.
	 * 
	 * @return the blast resistance of that material.
	 */
	@SuppressWarnings("deprecation")
	public static float getBlastResistance(Material material) {
		try {
			return material.getBlastResistance();
		} catch (Exception e) {
			switch (material) {
			// <editor-fold defaultstate="collapsed" desc="getBlastResistance">
			case ACACIA_BOAT:
			case ACACIA_SAPLING:
			case AIR:
			case ALLIUM:
			case APPLE:
			case ARMOR_STAND:
			case ARROW:
			case ATTACHED_MELON_STEM:
			case ATTACHED_PUMPKIN_STEM:
			case AZURE_BLUET:
			case BAKED_POTATO:
			case BAT_SPAWN_EGG:
			case BEEF:
			case BEETROOT:
			case BEETROOTS:
			case BEETROOT_SEEDS:
			case BEETROOT_SOUP:
			case BIRCH_BOAT:
			case BIRCH_SAPLING:
			case BLAZE_POWDER:
			case BLAZE_ROD:
			case BLAZE_SPAWN_EGG:
			case BLUE_ORCHID:
			case BONE:
			case BONE_MEAL:
			case BOOK:
			case BOW:
			case BOWL:
			case BRAIN_CORAL:
			case BRAIN_CORAL_FAN:
			case BRAIN_CORAL_WALL_FAN:
			case BREAD:
			case BRICK:
			case BROWN_MUSHROOM:
			case BUBBLE_COLUMN:
			case BUBBLE_CORAL:
			case BUBBLE_CORAL_FAN:
			case BUBBLE_CORAL_WALL_FAN:
			case BUCKET:
			case CACTUS_GREEN:
			case CARROT:
			case CARROTS:
			case CARROT_ON_A_STICK:
			case CAVE_AIR:
			case CAVE_SPIDER_SPAWN_EGG:
			case CHAINMAIL_BOOTS:
			case CHAINMAIL_CHESTPLATE:
			case CHAINMAIL_HELMET:
			case CHAINMAIL_LEGGINGS:
			case CHARCOAL:
			case CHEST_MINECART:
			case CHICKEN:
			case CHICKEN_SPAWN_EGG:
			case CHORUS_FRUIT:
			case CLAY_BALL:
			case CLOCK:
			case COAL:
			case COCOA_BEANS:
			case COD:
			case COD_BUCKET:
			case COD_SPAWN_EGG:
			case COMMAND_BLOCK_MINECART:
			case COMPARATOR:
			case COMPASS:
			case COOKED_BEEF:
			case COOKED_CHICKEN:
			case COOKED_COD:
			case COOKED_MUTTON:
			case COOKED_PORKCHOP:
			case COOKED_RABBIT:
			case COOKED_SALMON:
			case COOKIE:
			case COW_SPAWN_EGG:
			case CREEPER_SPAWN_EGG:
			case CYAN_DYE:
			case DANDELION:
			case DANDELION_YELLOW:
			case DARK_OAK_BOAT:
			case DARK_OAK_SAPLING:
			case DEAD_BRAIN_CORAL_FAN:
			case DEAD_BRAIN_CORAL_WALL_FAN:
			case DEAD_BUBBLE_CORAL_FAN:
			case DEAD_BUBBLE_CORAL_WALL_FAN:
			case DEAD_BUSH:
			case DEAD_FIRE_CORAL_FAN:
			case DEAD_FIRE_CORAL_WALL_FAN:
			case DEAD_HORN_CORAL_FAN:
			case DEAD_HORN_CORAL_WALL_FAN:
			case DEAD_TUBE_CORAL_FAN:
			case DEAD_TUBE_CORAL_WALL_FAN:
			case DEBUG_STICK:
			case DIAMOND:
			case DIAMOND_AXE:
			case DIAMOND_BOOTS:
			case DIAMOND_CHESTPLATE:
			case DIAMOND_HELMET:
			case DIAMOND_HOE:
			case DIAMOND_HORSE_ARMOR:
			case DIAMOND_LEGGINGS:
			case DIAMOND_PICKAXE:
			case DIAMOND_SHOVEL:
			case DIAMOND_SWORD:
			case DOLPHIN_SPAWN_EGG:
			case DONKEY_SPAWN_EGG:
			case DRAGON_BREATH:
			case DRIED_KELP:
			case DROWNED_SPAWN_EGG:
			case EGG:
			case ELDER_GUARDIAN_SPAWN_EGG:
			case ELYTRA:
			case EMERALD:
			case ENCHANTED_BOOK:
			case ENCHANTED_GOLDEN_APPLE:
			case ENDERMAN_SPAWN_EGG:
			case ENDERMITE_SPAWN_EGG:
			case ENDER_EYE:
			case ENDER_PEARL:
			case END_CRYSTAL:
			case END_ROD:
			case EVOKER_SPAWN_EGG:
			case EXPERIENCE_BOTTLE:
			case FEATHER:
			case FERMENTED_SPIDER_EYE:
			case FERN:
			case FILLED_MAP:
			case FIRE:
			case FIREWORK_ROCKET:
			case FIREWORK_STAR:
			case FIRE_CHARGE:
			case FIRE_CORAL:
			case FIRE_CORAL_FAN:
			case FIRE_CORAL_WALL_FAN:
			case FISHING_ROD:
			case FLINT:
			case FLINT_AND_STEEL:
			case FLOWER_POT:
			case FURNACE_MINECART:
			case GHAST_SPAWN_EGG:
			case GHAST_TEAR:
			case GLASS_BOTTLE:
			case GLISTERING_MELON_SLICE:
			case GLOWSTONE_DUST:
			case GOLDEN_APPLE:
			case GOLDEN_AXE:
			case GOLDEN_BOOTS:
			case GOLDEN_CARROT:
			case GOLDEN_CHESTPLATE:
			case GOLDEN_HELMET:
			case GOLDEN_HOE:
			case GOLDEN_HORSE_ARMOR:
			case GOLDEN_LEGGINGS:
			case GOLDEN_PICKAXE:
			case GOLDEN_SHOVEL:
			case GOLDEN_SWORD:
			case GOLD_INGOT:
			case GOLD_NUGGET:
			case GRASS:
			case GRAY_DYE:
			case GUARDIAN_SPAWN_EGG:
			case GUNPOWDER:
			case HEART_OF_THE_SEA:
			case HOPPER_MINECART:
			case HORN_CORAL:
			case HORN_CORAL_FAN:
			case HORN_CORAL_WALL_FAN:
			case HORSE_SPAWN_EGG:
			case HUSK_SPAWN_EGG:
			case INK_SAC:
			case IRON_AXE:
			case IRON_BOOTS:
			case IRON_CHESTPLATE:
			case IRON_HELMET:
			case IRON_HOE:
			case IRON_HORSE_ARMOR:
			case IRON_INGOT:
			case IRON_LEGGINGS:
			case IRON_NUGGET:
			case IRON_PICKAXE:
			case IRON_SHOVEL:
			case IRON_SWORD:
			case ITEM_FRAME:
			case JUNGLE_BOAT:
			case JUNGLE_SAPLING:
			case KELP:
			case KELP_PLANT:
			case KNOWLEDGE_BOOK:
			case LAPIS_LAZULI:
			case LARGE_FERN:
			case LAVA_BUCKET:
			case LEAD:
			case LEATHER:
			case LEATHER_BOOTS:
			case LEATHER_CHESTPLATE:
			case LEATHER_HELMET:
			case LEATHER_LEGGINGS:
			case LIGHT_BLUE_DYE:
			case LIGHT_GRAY_DYE:
			case LILAC:
			case LILY_PAD:
			case LIME_DYE:
			case LINGERING_POTION:
			case LLAMA_SPAWN_EGG:
			case MAGENTA_DYE:
			case MAGMA_CREAM:
			case MAGMA_CUBE_SPAWN_EGG:
			case MAP:
			case MELON_SEEDS:
			case MELON_SLICE:
			case MELON_STEM:
			case MILK_BUCKET:
			case MINECART:
			case MOOSHROOM_SPAWN_EGG:
			case MOVING_PISTON:
			case MULE_SPAWN_EGG:
			case MUSHROOM_STEW:
			case MUSIC_DISC_11:
			case MUSIC_DISC_13:
			case MUSIC_DISC_BLOCKS:
			case MUSIC_DISC_CAT:
			case MUSIC_DISC_CHIRP:
			case MUSIC_DISC_FAR:
			case MUSIC_DISC_MALL:
			case MUSIC_DISC_MELLOHI:
			case MUSIC_DISC_STAL:
			case MUSIC_DISC_STRAD:
			case MUSIC_DISC_WAIT:
			case MUSIC_DISC_WARD:
			case MUTTON:
			case NAME_TAG:
			case NAUTILUS_SHELL:
			case NETHER_BRICK:
			case NETHER_PORTAL:
			case NETHER_STAR:
			case NETHER_WART:
			case OAK_BOAT:
			case OAK_SAPLING:
			case OCELOT_SPAWN_EGG:
			case ORANGE_DYE:
			case ORANGE_TULIP:
			case OXEYE_DAISY:
			case PAINTING:
			case PAPER:
			case PARROT_SPAWN_EGG:
			case PEONY:
			case PHANTOM_MEMBRANE:
			case PHANTOM_SPAWN_EGG:
			case PIG_SPAWN_EGG:
			case PINK_DYE:
			case PINK_TULIP:
			case POISONOUS_POTATO:
			case POLAR_BEAR_SPAWN_EGG:
			case POPPED_CHORUS_FRUIT:
			case POPPY:
			case PORKCHOP:
			case POTATO:
			case POTATOES:
			case POTION:
			case POTTED_ACACIA_SAPLING:
			case POTTED_ALLIUM:
			case POTTED_AZURE_BLUET:
			case POTTED_BIRCH_SAPLING:
			case POTTED_BLUE_ORCHID:
			case POTTED_BROWN_MUSHROOM:
			case POTTED_CACTUS:
			case POTTED_DANDELION:
			case POTTED_DARK_OAK_SAPLING:
			case POTTED_DEAD_BUSH:
			case POTTED_FERN:
			case POTTED_JUNGLE_SAPLING:
			case POTTED_OAK_SAPLING:
			case POTTED_ORANGE_TULIP:
			case POTTED_OXEYE_DAISY:
			case POTTED_PINK_TULIP:
			case POTTED_POPPY:
			case POTTED_RED_MUSHROOM:
			case POTTED_RED_TULIP:
			case POTTED_SPRUCE_SAPLING:
			case POTTED_WHITE_TULIP:
			case PRISMARINE_CRYSTALS:
			case PRISMARINE_SHARD:
			case PUFFERFISH:
			case PUFFERFISH_BUCKET:
			case PUFFERFISH_SPAWN_EGG:
			case PUMPKIN_PIE:
			case PUMPKIN_SEEDS:
			case PUMPKIN_STEM:
			case PURPLE_DYE:
			case QUARTZ:
			case RABBIT:
			case RABBIT_FOOT:
			case RABBIT_HIDE:
			case RABBIT_SPAWN_EGG:
			case RABBIT_STEW:
			case REDSTONE:
			case REDSTONE_TORCH:
			case REDSTONE_WALL_TORCH:
			case REDSTONE_WIRE:
			case RED_MUSHROOM:
			case RED_TULIP:
			case REPEATER:
			case ROSE_BUSH:
			case ROSE_RED:
			case ROTTEN_FLESH:
			case SADDLE:
			case SALMON:
			case SALMON_BUCKET:
			case SALMON_SPAWN_EGG:
			case SCUTE:
			case SEAGRASS:
			case SEA_PICKLE:
			case SHEARS:
			case SHEEP_SPAWN_EGG:
			case SHIELD:
			case SHULKER_SHELL:
			case SHULKER_SPAWN_EGG:
			case SILVERFISH_SPAWN_EGG:
			case SKELETON_HORSE_SPAWN_EGG:
			case SKELETON_SPAWN_EGG:
			case SLIME_BALL:
			case SLIME_BLOCK:
			case SLIME_SPAWN_EGG:
			case SNOWBALL:
			case SPECTRAL_ARROW:
			case SPIDER_EYE:
			case SPIDER_SPAWN_EGG:
			case SPLASH_POTION:
			case SPRUCE_BOAT:
			case SPRUCE_SAPLING:
			case SQUID_SPAWN_EGG:
			case STICK:
			case STONE_AXE:
			case STONE_HOE:
			case STONE_PICKAXE:
			case STONE_SHOVEL:
			case STONE_SWORD:
			case STRAY_SPAWN_EGG:
			case STRING:
			case STRUCTURE_VOID:
			case SUGAR:
			case SUGAR_CANE:
			case SUNFLOWER:
			case TALL_GRASS:
			case TALL_SEAGRASS:
			case TIPPED_ARROW:
			case TNT:
			case TNT_MINECART:
			case TORCH:
			case TOTEM_OF_UNDYING:
			case TRIDENT:
			case TRIPWIRE:
			case TRIPWIRE_HOOK:
			case TROPICAL_FISH:
			case TROPICAL_FISH_BUCKET:
			case TROPICAL_FISH_SPAWN_EGG:
			case TUBE_CORAL:
			case TUBE_CORAL_FAN:
			case TUBE_CORAL_WALL_FAN:
			case TURTLE_HELMET:
			case TURTLE_SPAWN_EGG:
			case VEX_SPAWN_EGG:
			case VILLAGER_SPAWN_EGG:
			case VINDICATOR_SPAWN_EGG:
			case VOID_AIR:
			case WALL_TORCH:
			case WATER_BUCKET:
			case WHEAT:
			case WHEAT_SEEDS:
			case WHITE_TULIP:
			case WITCH_SPAWN_EGG:
			case WITHER_SKELETON_SPAWN_EGG:
			case WOLF_SPAWN_EGG:
			case WOODEN_AXE:
			case WOODEN_HOE:
			case WOODEN_PICKAXE:
			case WOODEN_SHOVEL:
			case WOODEN_SWORD:
			case WRITABLE_BOOK:
			case WRITTEN_BOOK:
			case ZOMBIE_HORSE_SPAWN_EGG:
			case ZOMBIE_PIGMAN_SPAWN_EGG:
			case ZOMBIE_SPAWN_EGG:
			case ZOMBIE_VILLAGER_SPAWN_EGG:
				return 0.0F;
			case BLACK_CARPET:
			case BLUE_CARPET:
			case BROWN_CARPET:
			case CYAN_CARPET:
			case GRAY_CARPET:
			case GREEN_CARPET:
			case LIGHT_BLUE_CARPET:
			case LIGHT_GRAY_CARPET:
			case LIME_CARPET:
			case MAGENTA_CARPET:
			case ORANGE_CARPET:
			case PINK_CARPET:
			case PURPLE_CARPET:
			case RED_CARPET:
			case SNOW:
			case WHITE_CARPET:
			case YELLOW_CARPET:
				return 0.1F;
			case ACACIA_LEAVES:
			case BIRCH_LEAVES:
			case BLACK_BED:
			case BLUE_BED:
			case BROWN_BED:
			case BROWN_MUSHROOM_BLOCK:
			case CYAN_BED:
			case DARK_OAK_LEAVES:
			case DAYLIGHT_DETECTOR:
			case GRAY_BED:
			case GREEN_BED:
			case JUNGLE_LEAVES:
			case LIGHT_BLUE_BED:
			case LIGHT_GRAY_BED:
			case LIME_BED:
			case MAGENTA_BED:
			case MUSHROOM_STEM:
			case OAK_LEAVES:
			case ORANGE_BED:
			case PINK_BED:
			case PURPLE_BED:
			case RED_BED:
			case RED_MUSHROOM_BLOCK:
			case SNOW_BLOCK:
			case SPRUCE_LEAVES:
			case VINE:
			case WHITE_BED:
			case YELLOW_BED:
				return 0.2F;
			case BLACK_STAINED_GLASS:
			case BLACK_STAINED_GLASS_PANE:
			case BLUE_STAINED_GLASS:
			case BLUE_STAINED_GLASS_PANE:
			case BROWN_STAINED_GLASS:
			case BROWN_STAINED_GLASS_PANE:
			case CYAN_STAINED_GLASS:
			case CYAN_STAINED_GLASS_PANE:
			case GLASS:
			case GLASS_PANE:
			case GLOWSTONE:
			case GRAY_STAINED_GLASS:
			case GRAY_STAINED_GLASS_PANE:
			case GREEN_STAINED_GLASS:
			case GREEN_STAINED_GLASS_PANE:
			case LIGHT_BLUE_STAINED_GLASS:
			case LIGHT_BLUE_STAINED_GLASS_PANE:
			case LIGHT_GRAY_STAINED_GLASS:
			case LIGHT_GRAY_STAINED_GLASS_PANE:
			case LIME_STAINED_GLASS:
			case LIME_STAINED_GLASS_PANE:
			case MAGENTA_STAINED_GLASS:
			case MAGENTA_STAINED_GLASS_PANE:
			case ORANGE_STAINED_GLASS:
			case ORANGE_STAINED_GLASS_PANE:
			case PINK_STAINED_GLASS:
			case PINK_STAINED_GLASS_PANE:
			case PURPLE_STAINED_GLASS:
			case PURPLE_STAINED_GLASS_PANE:
			case REDSTONE_LAMP:
			case RED_STAINED_GLASS:
			case RED_STAINED_GLASS_PANE:
			case SEA_LANTERN:
			case WHITE_STAINED_GLASS:
			case WHITE_STAINED_GLASS_PANE:
			case YELLOW_STAINED_GLASS:
			case YELLOW_STAINED_GLASS_PANE:
				return 0.3F;
			case CACTUS:
			case CHORUS_FLOWER:
			case CHORUS_PLANT:
			case LADDER:
			case NETHERRACK:
				return 0.4F;
			case ACACIA_BUTTON:
			case ACACIA_PRESSURE_PLATE:
			case BIRCH_BUTTON:
			case BIRCH_PRESSURE_PLATE:
			case BLACK_CONCRETE_POWDER:
			case BLUE_CONCRETE_POWDER:
			case BREWING_STAND:
			case BROWN_CONCRETE_POWDER:
			case CAKE:
			case COARSE_DIRT:
			case CYAN_CONCRETE_POWDER:
			case DARK_OAK_BUTTON:
			case DARK_OAK_PRESSURE_PLATE:
			case DIRT:
			case FROSTED_ICE:
			case GRAY_CONCRETE_POWDER:
			case GREEN_CONCRETE_POWDER:
			case HAY_BLOCK:
			case HEAVY_WEIGHTED_PRESSURE_PLATE:
			case ICE:
			case JUNGLE_BUTTON:
			case JUNGLE_PRESSURE_PLATE:
			case LEVER:
			case LIGHT_BLUE_CONCRETE_POWDER:
			case LIGHT_GRAY_CONCRETE_POWDER:
			case LIGHT_WEIGHTED_PRESSURE_PLATE:
			case LIME_CONCRETE_POWDER:
			case MAGENTA_CONCRETE_POWDER:
			case MAGMA_BLOCK:
			case OAK_BUTTON:
			case OAK_PRESSURE_PLATE:
			case ORANGE_CONCRETE_POWDER:
			case PACKED_ICE:
			case PINK_CONCRETE_POWDER:
			case PISTON:
			case PISTON_HEAD:
			case PODZOL:
			case PURPLE_CONCRETE_POWDER:
			case RED_CONCRETE_POWDER:
			case RED_SAND:
			case SAND:
			case SOUL_SAND:
			case SPRUCE_BUTTON:
			case SPRUCE_PRESSURE_PLATE:
			case STICKY_PISTON:
			case STONE_BUTTON:
			case STONE_PRESSURE_PLATE:
			case TURTLE_EGG:
			case WHITE_CONCRETE_POWDER:
			case YELLOW_CONCRETE_POWDER:
				return 0.5F;
			case CLAY:
			case FARMLAND:
			case GRASS_BLOCK:
			case GRAVEL:
			case MYCELIUM:
			case SPONGE:
			case WET_SPONGE:
				return 0.6F;
			case GRASS_PATH:
				return 0.65F;
			case ACTIVATOR_RAIL:
			case DETECTOR_RAIL:
			case POWERED_RAIL:
			case RAIL:
				return 0.7F;
			case INFESTED_CHISELED_STONE_BRICKS:
			case INFESTED_COBBLESTONE:
			case INFESTED_CRACKED_STONE_BRICKS:
			case INFESTED_MOSSY_STONE_BRICKS:
			case INFESTED_STONE:
			case INFESTED_STONE_BRICKS:
				return 0.75F;
			case BLACK_WOOL:
			case BLUE_WOOL:
			case BROWN_WOOL:
			case CHISELED_QUARTZ_BLOCK:
			case CHISELED_RED_SANDSTONE:
			case CHISELED_SANDSTONE:
			case CUT_RED_SANDSTONE:
			case CUT_SANDSTONE:
			case CYAN_WOOL:
			case END_STONE_BRICKS:
			case GRAY_WOOL:
			case GREEN_WOOL:
			case LIGHT_BLUE_WOOL:
			case LIGHT_GRAY_WOOL:
			case LIME_WOOL:
			case MAGENTA_WOOL:
			case NOTE_BLOCK:
			case ORANGE_WOOL:
			case PINK_WOOL:
			case PURPLE_WOOL:
			case QUARTZ_BLOCK:
			case QUARTZ_PILLAR:
			case QUARTZ_STAIRS:
			case RED_SANDSTONE:
			case RED_SANDSTONE_STAIRS:
			case RED_WOOL:
			case SANDSTONE:
			case SANDSTONE_STAIRS:
			case WHITE_WOOL:
			case YELLOW_WOOL:
				return 0.8F;
			case BLACK_BANNER:
			case BLACK_WALL_BANNER:
			case BLUE_BANNER:
			case BLUE_WALL_BANNER:
			case BROWN_BANNER:
			case BROWN_WALL_BANNER:
			case CARVED_PUMPKIN:
			case CREEPER_HEAD:
			case CREEPER_WALL_HEAD:
			case CYAN_BANNER:
			case CYAN_WALL_BANNER:
			case DRAGON_HEAD:
			case DRAGON_WALL_HEAD:
			case GRAY_BANNER:
			case GRAY_WALL_BANNER:
			case GREEN_BANNER:
			case GREEN_WALL_BANNER:
			case JACK_O_LANTERN:
			case LIGHT_BLUE_BANNER:
			case LIGHT_BLUE_WALL_BANNER:
			case LIGHT_GRAY_BANNER:
			case LIGHT_GRAY_WALL_BANNER:
			case LIME_BANNER:
			case LIME_WALL_BANNER:
			case MAGENTA_BANNER:
			case MAGENTA_WALL_BANNER:
			case MELON:
			case NETHER_WART_BLOCK:
			case ORANGE_BANNER:
			case ORANGE_WALL_BANNER:
			case PINK_BANNER:
			case PINK_WALL_BANNER:
			case PLAYER_HEAD:
			case PLAYER_WALL_HEAD:
			case PUMPKIN:
			case PURPLE_BANNER:
			case PURPLE_WALL_BANNER:
			case RED_BANNER:
			case RED_WALL_BANNER:
			case SIGN:
			case SKELETON_SKULL:
			case SKELETON_WALL_SKULL:
			case WALL_SIGN:
			case WHITE_BANNER:
			case WHITE_WALL_BANNER:
			case WITHER_SKELETON_SKULL:
			case WITHER_SKELETON_WALL_SKULL:
			case YELLOW_BANNER:
			case YELLOW_WALL_BANNER:
			case ZOMBIE_HEAD:
			case ZOMBIE_WALL_HEAD:
				return 1.0F;
			case BLACK_GLAZED_TERRACOTTA:
			case BLUE_GLAZED_TERRACOTTA:
			case BROWN_GLAZED_TERRACOTTA:
			case CYAN_GLAZED_TERRACOTTA:
			case GRAY_GLAZED_TERRACOTTA:
			case GREEN_GLAZED_TERRACOTTA:
			case LIGHT_BLUE_GLAZED_TERRACOTTA:
			case LIGHT_GRAY_GLAZED_TERRACOTTA:
			case LIME_GLAZED_TERRACOTTA:
			case MAGENTA_GLAZED_TERRACOTTA:
			case ORANGE_GLAZED_TERRACOTTA:
			case PINK_GLAZED_TERRACOTTA:
			case PURPLE_GLAZED_TERRACOTTA:
			case RED_GLAZED_TERRACOTTA:
			case WHITE_GLAZED_TERRACOTTA:
			case YELLOW_GLAZED_TERRACOTTA:
				return 1.4F;
			case BOOKSHELF:
				return 1.5F;
			case BLACK_CONCRETE:
			case BLUE_CONCRETE:
			case BROWN_CONCRETE:
			case CYAN_CONCRETE:
			case GRAY_CONCRETE:
			case GREEN_CONCRETE:
			case LIGHT_BLUE_CONCRETE:
			case LIGHT_GRAY_CONCRETE:
			case LIME_CONCRETE:
			case MAGENTA_CONCRETE:
			case ORANGE_CONCRETE:
			case PINK_CONCRETE:
			case PURPLE_CONCRETE:
			case RED_CONCRETE:
			case WHITE_CONCRETE:
			case YELLOW_CONCRETE:
				return 1.8F;
			case ACACIA_LOG:
			case ACACIA_WOOD:
			case BIRCH_LOG:
			case BIRCH_WOOD:
			case BLACK_SHULKER_BOX:
			case BLUE_SHULKER_BOX:
			case BONE_BLOCK:
			case BROWN_SHULKER_BOX:
			case CAULDRON:
			case CYAN_SHULKER_BOX:
			case DARK_OAK_LOG:
			case DARK_OAK_WOOD:
			case GRAY_SHULKER_BOX:
			case GREEN_SHULKER_BOX:
			case JUNGLE_LOG:
			case JUNGLE_WOOD:
			case LIGHT_BLUE_SHULKER_BOX:
			case LIGHT_GRAY_SHULKER_BOX:
			case LIME_SHULKER_BOX:
			case MAGENTA_SHULKER_BOX:
			case OAK_LOG:
			case OAK_WOOD:
			case ORANGE_SHULKER_BOX:
			case PINK_SHULKER_BOX:
			case PURPLE_SHULKER_BOX:
			case RED_SHULKER_BOX:
			case SHULKER_BOX:
			case SPRUCE_LOG:
			case SPRUCE_WOOD:
			case STRIPPED_ACACIA_LOG:
			case STRIPPED_ACACIA_WOOD:
			case STRIPPED_BIRCH_LOG:
			case STRIPPED_BIRCH_WOOD:
			case STRIPPED_DARK_OAK_LOG:
			case STRIPPED_DARK_OAK_WOOD:
			case STRIPPED_JUNGLE_LOG:
			case STRIPPED_JUNGLE_WOOD:
			case STRIPPED_OAK_LOG:
			case STRIPPED_OAK_WOOD:
			case STRIPPED_SPRUCE_LOG:
			case STRIPPED_SPRUCE_WOOD:
			case WHITE_SHULKER_BOX:
			case YELLOW_SHULKER_BOX:
				return 2.0F;
			case CHEST:
			case CRAFTING_TABLE:
			case DRIED_KELP_BLOCK:
			case TRAPPED_CHEST:
				return 2.5F;
			case BLUE_ICE:
				return 2.8F;
			case ACACIA_DOOR:
			case ACACIA_FENCE:
			case ACACIA_FENCE_GATE:
			case ACACIA_PLANKS:
			case ACACIA_SLAB:
			case ACACIA_STAIRS:
			case ACACIA_TRAPDOOR:
			case BEACON:
			case BIRCH_DOOR:
			case BIRCH_FENCE:
			case BIRCH_FENCE_GATE:
			case BIRCH_PLANKS:
			case BIRCH_SLAB:
			case BIRCH_STAIRS:
			case BIRCH_TRAPDOOR:
			case COAL_ORE:
			case COCOA:
			case CONDUIT:
			case DARK_OAK_DOOR:
			case DARK_OAK_FENCE:
			case DARK_OAK_FENCE_GATE:
			case DARK_OAK_PLANKS:
			case DARK_OAK_SLAB:
			case DARK_OAK_STAIRS:
			case DARK_OAK_TRAPDOOR:
			case DIAMOND_ORE:
			case EMERALD_ORE:
			case GOLD_ORE:
			case IRON_ORE:
			case JUNGLE_DOOR:
			case JUNGLE_FENCE:
			case JUNGLE_FENCE_GATE:
			case JUNGLE_PLANKS:
			case JUNGLE_SLAB:
			case JUNGLE_STAIRS:
			case JUNGLE_TRAPDOOR:
			case LAPIS_BLOCK:
			case LAPIS_ORE:
			case NETHER_QUARTZ_ORE:
			case OAK_DOOR:
			case OAK_FENCE:
			case OAK_FENCE_GATE:
			case OAK_PLANKS:
			case OAK_SLAB:
			case OAK_STAIRS:
			case OAK_TRAPDOOR:
			case OBSERVER:
			case REDSTONE_ORE:
			case SPRUCE_DOOR:
			case SPRUCE_FENCE:
			case SPRUCE_FENCE_GATE:
			case SPRUCE_PLANKS:
			case SPRUCE_SLAB:
			case SPRUCE_STAIRS:
			case SPRUCE_TRAPDOOR:
				return 3.0F;
			case DISPENSER:
			case DROPPER:
			case FURNACE:
				return 3.5F;
			case COBWEB:
				return 4.0F;
			case BLACK_TERRACOTTA:
			case BLUE_TERRACOTTA:
			case BROWN_TERRACOTTA:
			case CYAN_TERRACOTTA:
			case GRAY_TERRACOTTA:
			case GREEN_TERRACOTTA:
			case LIGHT_BLUE_TERRACOTTA:
			case LIGHT_GRAY_TERRACOTTA:
			case LIME_TERRACOTTA:
			case MAGENTA_TERRACOTTA:
			case ORANGE_TERRACOTTA:
			case PINK_TERRACOTTA:
			case PURPLE_TERRACOTTA:
			case RED_TERRACOTTA:
			case TERRACOTTA:
			case WHITE_TERRACOTTA:
			case YELLOW_TERRACOTTA:
				return 4.2F;
			case HOPPER:
				return 4.8F;
			case IRON_DOOR:
			case IRON_TRAPDOOR:
			case SPAWNER:
				return 5.0F;
			case ANDESITE:
			case BRAIN_CORAL_BLOCK:
			case BRICKS:
			case BRICK_SLAB:
			case BRICK_STAIRS:
			case BUBBLE_CORAL_BLOCK:
			case CHISELED_STONE_BRICKS:
			case COAL_BLOCK:
			case COBBLESTONE:
			case COBBLESTONE_SLAB:
			case COBBLESTONE_STAIRS:
			case COBBLESTONE_WALL:
			case CRACKED_STONE_BRICKS:
			case DARK_PRISMARINE:
			case DARK_PRISMARINE_SLAB:
			case DARK_PRISMARINE_STAIRS:
			case DEAD_BRAIN_CORAL_BLOCK:
			case DEAD_BUBBLE_CORAL_BLOCK:
			case DEAD_FIRE_CORAL_BLOCK:
			case DEAD_HORN_CORAL_BLOCK:
			case DEAD_TUBE_CORAL_BLOCK:
			case DIAMOND_BLOCK:
			case DIORITE:
			case EMERALD_BLOCK:
			case FIRE_CORAL_BLOCK:
			case GOLD_BLOCK:
			case GRANITE:
			case HORN_CORAL_BLOCK:
			case IRON_BARS:
			case IRON_BLOCK:
			case JUKEBOX:
			case MOSSY_COBBLESTONE:
			case MOSSY_COBBLESTONE_WALL:
			case MOSSY_STONE_BRICKS:
			case NETHER_BRICKS:
			case NETHER_BRICK_FENCE:
			case NETHER_BRICK_SLAB:
			case NETHER_BRICK_STAIRS:
			case PETRIFIED_OAK_SLAB:
			case POLISHED_ANDESITE:
			case POLISHED_DIORITE:
			case POLISHED_GRANITE:
			case PRISMARINE:
			case PRISMARINE_BRICKS:
			case PRISMARINE_BRICK_SLAB:
			case PRISMARINE_BRICK_STAIRS:
			case PRISMARINE_SLAB:
			case PRISMARINE_STAIRS:
			case PURPUR_BLOCK:
			case PURPUR_PILLAR:
			case PURPUR_SLAB:
			case PURPUR_STAIRS:
			case QUARTZ_SLAB:
			case REDSTONE_BLOCK:
			case RED_NETHER_BRICKS:
			case RED_SANDSTONE_SLAB:
			case SANDSTONE_SLAB:
			case SMOOTH_QUARTZ:
			case SMOOTH_RED_SANDSTONE:
			case SMOOTH_SANDSTONE:
			case SMOOTH_STONE:
			case STONE:
			case STONE_BRICKS:
			case STONE_BRICK_SLAB:
			case STONE_BRICK_STAIRS:
			case STONE_SLAB:
			case TUBE_CORAL_BLOCK:
				return 6.0F;
			case DRAGON_EGG:
			case END_STONE:
				return 9.0F;
			case LAVA:
			case WATER:
				return 100.0F;
			case ENDER_CHEST:
				return 600.0F;
			case ANVIL:
			case CHIPPED_ANVIL:
			case DAMAGED_ANVIL:
			case ENCHANTING_TABLE:
			case OBSIDIAN:
				return 1200.0F;
			case BEDROCK:
			case CHAIN_COMMAND_BLOCK:
			case COMMAND_BLOCK:
			case END_GATEWAY:
			case END_PORTAL:
			case END_PORTAL_FRAME:
			case REPEATING_COMMAND_BLOCK:
			case STRUCTURE_BLOCK:
				return 3600000.0F;
			case BARRIER:
				return 3600000.8F;
			// --- Legacy Seperator ---
			case LEGACY_AIR:
			case LEGACY_SAPLING:
			case LEGACY_LONG_GRASS:
			case LEGACY_DEAD_BUSH:
			case LEGACY_PISTON_MOVING_PIECE:
			case LEGACY_YELLOW_FLOWER:
			case LEGACY_RED_ROSE:
			case LEGACY_BROWN_MUSHROOM:
			case LEGACY_RED_MUSHROOM:
			case LEGACY_TNT:
			case LEGACY_TORCH:
			case LEGACY_FIRE:
			case LEGACY_REDSTONE_WIRE:
			case LEGACY_CROPS:
			case LEGACY_BURNING_FURNACE:
			case LEGACY_WALL_SIGN:
			case LEGACY_REDSTONE_TORCH_OFF:
			case LEGACY_REDSTONE_TORCH_ON:
			case LEGACY_SUGAR_CANE_BLOCK:
			case LEGACY_PORTAL:
			case LEGACY_DIODE_BLOCK_OFF:
			case LEGACY_DIODE_BLOCK_ON:
			case LEGACY_PUMPKIN_STEM:
			case LEGACY_MELON_STEM:
			case LEGACY_WATER_LILY:
			case LEGACY_NETHER_WARTS:
			case LEGACY_TRIPWIRE_HOOK:
			case LEGACY_TRIPWIRE:
			case LEGACY_FLOWER_POT:
			case LEGACY_CARROT:
			case LEGACY_POTATO:
			case LEGACY_SKULL:
			case LEGACY_REDSTONE_COMPARATOR_OFF:
			case LEGACY_REDSTONE_COMPARATOR_ON:
			case LEGACY_SLIME_BLOCK:
			case LEGACY_DOUBLE_PLANT:
			case LEGACY_WALL_BANNER:
			case LEGACY_END_ROD:
			case LEGACY_BEETROOT_BLOCK:
			case LEGACY_STRUCTURE_VOID:
			case LEGACY_IRON_SPADE:
			case LEGACY_IRON_PICKAXE:
			case LEGACY_IRON_AXE:
			case LEGACY_FLINT_AND_STEEL:
			case LEGACY_APPLE:
			case LEGACY_BOW:
			case LEGACY_ARROW:
			case LEGACY_COAL:
			case LEGACY_DIAMOND:
			case LEGACY_IRON_INGOT:
			case LEGACY_GOLD_INGOT:
			case LEGACY_IRON_SWORD:
			case LEGACY_WOOD_SWORD:
			case LEGACY_WOOD_SPADE:
			case LEGACY_WOOD_PICKAXE:
			case LEGACY_WOOD_AXE:
			case LEGACY_STONE_SWORD:
			case LEGACY_STONE_SPADE:
			case LEGACY_STONE_PICKAXE:
			case LEGACY_STONE_AXE:
			case LEGACY_DIAMOND_SWORD:
			case LEGACY_DIAMOND_SPADE:
			case LEGACY_DIAMOND_PICKAXE:
			case LEGACY_DIAMOND_AXE:
			case LEGACY_STICK:
			case LEGACY_BOWL:
			case LEGACY_MUSHROOM_SOUP:
			case LEGACY_GOLD_SWORD:
			case LEGACY_GOLD_SPADE:
			case LEGACY_GOLD_PICKAXE:
			case LEGACY_GOLD_AXE:
			case LEGACY_STRING:
			case LEGACY_FEATHER:
			case LEGACY_SULPHUR:
			case LEGACY_WOOD_HOE:
			case LEGACY_STONE_HOE:
			case LEGACY_IRON_HOE:
			case LEGACY_DIAMOND_HOE:
			case LEGACY_GOLD_HOE:
			case LEGACY_SEEDS:
			case LEGACY_WHEAT:
			case LEGACY_BREAD:
			case LEGACY_LEATHER_HELMET:
			case LEGACY_LEATHER_CHESTPLATE:
			case LEGACY_LEATHER_LEGGINGS:
			case LEGACY_LEATHER_BOOTS:
			case LEGACY_CHAINMAIL_HELMET:
			case LEGACY_CHAINMAIL_CHESTPLATE:
			case LEGACY_CHAINMAIL_LEGGINGS:
			case LEGACY_CHAINMAIL_BOOTS:
			case LEGACY_IRON_HELMET:
			case LEGACY_IRON_CHESTPLATE:
			case LEGACY_IRON_LEGGINGS:
			case LEGACY_IRON_BOOTS:
			case LEGACY_DIAMOND_HELMET:
			case LEGACY_DIAMOND_CHESTPLATE:
			case LEGACY_DIAMOND_LEGGINGS:
			case LEGACY_DIAMOND_BOOTS:
			case LEGACY_GOLD_HELMET:
			case LEGACY_GOLD_CHESTPLATE:
			case LEGACY_GOLD_LEGGINGS:
			case LEGACY_GOLD_BOOTS:
			case LEGACY_FLINT:
			case LEGACY_PORK:
			case LEGACY_GRILLED_PORK:
			case LEGACY_PAINTING:
			case LEGACY_GOLDEN_APPLE:
			case LEGACY_BUCKET:
			case LEGACY_WATER_BUCKET:
			case LEGACY_LAVA_BUCKET:
			case LEGACY_MINECART:
			case LEGACY_SADDLE:
			case LEGACY_REDSTONE:
			case LEGACY_SNOW_BALL:
			case LEGACY_BOAT:
			case LEGACY_LEATHER:
			case LEGACY_MILK_BUCKET:
			case LEGACY_CLAY_BRICK:
			case LEGACY_CLAY_BALL:
			case LEGACY_SUGAR_CANE:
			case LEGACY_PAPER:
			case LEGACY_BOOK:
			case LEGACY_SLIME_BALL:
			case LEGACY_STORAGE_MINECART:
			case LEGACY_POWERED_MINECART:
			case LEGACY_EGG:
			case LEGACY_COMPASS:
			case LEGACY_FISHING_ROD:
			case LEGACY_WATCH:
			case LEGACY_GLOWSTONE_DUST:
			case LEGACY_RAW_FISH:
			case LEGACY_COOKED_FISH:
			case LEGACY_INK_SACK:
			case LEGACY_BONE:
			case LEGACY_SUGAR:
			case LEGACY_DIODE:
			case LEGACY_COOKIE:
			case LEGACY_MAP:
			case LEGACY_SHEARS:
			case LEGACY_MELON:
			case LEGACY_PUMPKIN_SEEDS:
			case LEGACY_MELON_SEEDS:
			case LEGACY_RAW_BEEF:
			case LEGACY_COOKED_BEEF:
			case LEGACY_RAW_CHICKEN:
			case LEGACY_COOKED_CHICKEN:
			case LEGACY_ROTTEN_FLESH:
			case LEGACY_ENDER_PEARL:
			case LEGACY_BLAZE_ROD:
			case LEGACY_GHAST_TEAR:
			case LEGACY_GOLD_NUGGET:
			case LEGACY_NETHER_STALK:
			case LEGACY_POTION:
			case LEGACY_GLASS_BOTTLE:
			case LEGACY_SPIDER_EYE:
			case LEGACY_FERMENTED_SPIDER_EYE:
			case LEGACY_BLAZE_POWDER:
			case LEGACY_MAGMA_CREAM:
			case LEGACY_EYE_OF_ENDER:
			case LEGACY_SPECKLED_MELON:
			case LEGACY_MONSTER_EGG:
			case LEGACY_EXP_BOTTLE:
			case LEGACY_FIREBALL:
			case LEGACY_BOOK_AND_QUILL:
			case LEGACY_WRITTEN_BOOK:
			case LEGACY_EMERALD:
			case LEGACY_ITEM_FRAME:
			case LEGACY_FLOWER_POT_ITEM:
			case LEGACY_CARROT_ITEM:
			case LEGACY_POTATO_ITEM:
			case LEGACY_BAKED_POTATO:
			case LEGACY_POISONOUS_POTATO:
			case LEGACY_EMPTY_MAP:
			case LEGACY_GOLDEN_CARROT:
			case LEGACY_CARROT_STICK:
			case LEGACY_NETHER_STAR:
			case LEGACY_PUMPKIN_PIE:
			case LEGACY_FIREWORK:
			case LEGACY_FIREWORK_CHARGE:
			case LEGACY_ENCHANTED_BOOK:
			case LEGACY_REDSTONE_COMPARATOR:
			case LEGACY_NETHER_BRICK_ITEM:
			case LEGACY_QUARTZ:
			case LEGACY_EXPLOSIVE_MINECART:
			case LEGACY_HOPPER_MINECART:
			case LEGACY_PRISMARINE_SHARD:
			case LEGACY_PRISMARINE_CRYSTALS:
			case LEGACY_RABBIT:
			case LEGACY_COOKED_RABBIT:
			case LEGACY_RABBIT_STEW:
			case LEGACY_RABBIT_FOOT:
			case LEGACY_RABBIT_HIDE:
			case LEGACY_ARMOR_STAND:
			case LEGACY_IRON_BARDING:
			case LEGACY_GOLD_BARDING:
			case LEGACY_DIAMOND_BARDING:
			case LEGACY_LEASH:
			case LEGACY_NAME_TAG:
			case LEGACY_COMMAND_MINECART:
			case LEGACY_MUTTON:
			case LEGACY_COOKED_MUTTON:
			case LEGACY_END_CRYSTAL:
			case LEGACY_CHORUS_FRUIT:
			case LEGACY_CHORUS_FRUIT_POPPED:
			case LEGACY_BEETROOT:
			case LEGACY_BEETROOT_SEEDS:
			case LEGACY_BEETROOT_SOUP:
			case LEGACY_DRAGONS_BREATH:
			case LEGACY_SPLASH_POTION:
			case LEGACY_SPECTRAL_ARROW:
			case LEGACY_TIPPED_ARROW:
			case LEGACY_LINGERING_POTION:
			case LEGACY_SHIELD:
			case LEGACY_ELYTRA:
			case LEGACY_BOAT_SPRUCE:
			case LEGACY_BOAT_BIRCH:
			case LEGACY_BOAT_JUNGLE:
			case LEGACY_BOAT_ACACIA:
			case LEGACY_BOAT_DARK_OAK:
			case LEGACY_TOTEM:
			case LEGACY_SHULKER_SHELL:
			case LEGACY_IRON_NUGGET:
			case LEGACY_KNOWLEDGE_BOOK:
			case LEGACY_GOLD_RECORD:
			case LEGACY_GREEN_RECORD:
			case LEGACY_RECORD_3:
			case LEGACY_RECORD_4:
			case LEGACY_RECORD_5:
			case LEGACY_RECORD_6:
			case LEGACY_RECORD_7:
			case LEGACY_RECORD_8:
			case LEGACY_RECORD_9:
			case LEGACY_RECORD_10:
			case LEGACY_RECORD_11:
			case LEGACY_RECORD_12:
				return 0.0F;
			case LEGACY_SNOW:
			case LEGACY_CARPET:
				return 0.1F;
			case LEGACY_LEAVES:
			case LEGACY_BED_BLOCK:
			case LEGACY_SNOW_BLOCK:
			case LEGACY_HUGE_MUSHROOM_1:
			case LEGACY_HUGE_MUSHROOM_2:
			case LEGACY_VINE:
			case LEGACY_DAYLIGHT_DETECTOR:
			case LEGACY_LEAVES_2:
			case LEGACY_DAYLIGHT_DETECTOR_INVERTED:
			case LEGACY_BED:
				return 0.2F;
			case LEGACY_GLASS:
			case LEGACY_GLOWSTONE:
			case LEGACY_STAINED_GLASS:
			case LEGACY_THIN_GLASS:
			case LEGACY_REDSTONE_LAMP_OFF:
			case LEGACY_REDSTONE_LAMP_ON:
			case LEGACY_STAINED_GLASS_PANE:
			case LEGACY_SEA_LANTERN:
				return 0.3F;
			case LEGACY_LADDER:
			case LEGACY_CACTUS:
			case LEGACY_NETHERRACK:
			case LEGACY_CHORUS_PLANT:
			case LEGACY_CHORUS_FLOWER:
				return 0.4F;
			case LEGACY_DIRT:
			case LEGACY_SAND:
			case LEGACY_PISTON_STICKY_BASE:
			case LEGACY_PISTON_BASE:
			case LEGACY_PISTON_EXTENSION:
			case LEGACY_LEVER:
			case LEGACY_STONE_PLATE:
			case LEGACY_WOOD_PLATE:
			case LEGACY_STONE_BUTTON:
			case LEGACY_ICE:
			case LEGACY_SOUL_SAND:
			case LEGACY_CAKE_BLOCK:
			case LEGACY_BREWING_STAND:
			case LEGACY_WOOD_BUTTON:
			case LEGACY_GOLD_PLATE:
			case LEGACY_IRON_PLATE:
			case LEGACY_HAY_BLOCK:
			case LEGACY_PACKED_ICE:
			case LEGACY_FROSTED_ICE:
			case LEGACY_MAGMA:
			case LEGACY_CONCRETE_POWDER:
			case LEGACY_CAKE:
			case LEGACY_BREWING_STAND_ITEM:
				return 0.5F;
			case LEGACY_GRASS:
			case LEGACY_GRAVEL:
			case LEGACY_SPONGE:
			case LEGACY_SOIL:
			case LEGACY_CLAY:
			case LEGACY_MYCEL:
				return 0.6F;
			case LEGACY_GRASS_PATH:
				return 0.65F;
			case LEGACY_POWERED_RAIL:
			case LEGACY_DETECTOR_RAIL:
			case LEGACY_RAILS:
			case LEGACY_ACTIVATOR_RAIL:
				return 0.7F;
			case LEGACY_MONSTER_EGGS:
				return 0.75F;
			case LEGACY_SANDSTONE:
			case LEGACY_NOTE_BLOCK:
			case LEGACY_WOOL:
			case LEGACY_SANDSTONE_STAIRS:
			case LEGACY_QUARTZ_BLOCK:
			case LEGACY_QUARTZ_STAIRS:
			case LEGACY_RED_SANDSTONE:
			case LEGACY_RED_SANDSTONE_STAIRS:
			case LEGACY_END_BRICKS:
				return 0.8F;
			case LEGACY_SIGN_POST:
			case LEGACY_PUMPKIN:
			case LEGACY_JACK_O_LANTERN:
			case LEGACY_MELON_BLOCK:
			case LEGACY_STANDING_BANNER:
			case LEGACY_NETHER_WART_BLOCK:
			case LEGACY_SIGN:
			case LEGACY_SKULL_ITEM:
			case LEGACY_BANNER:
				return 1.0F;
			case LEGACY_WHITE_GLAZED_TERRACOTTA:
			case LEGACY_ORANGE_GLAZED_TERRACOTTA:
			case LEGACY_MAGENTA_GLAZED_TERRACOTTA:
			case LEGACY_LIGHT_BLUE_GLAZED_TERRACOTTA:
			case LEGACY_YELLOW_GLAZED_TERRACOTTA:
			case LEGACY_LIME_GLAZED_TERRACOTTA:
			case LEGACY_PINK_GLAZED_TERRACOTTA:
			case LEGACY_GRAY_GLAZED_TERRACOTTA:
			case LEGACY_SILVER_GLAZED_TERRACOTTA:
			case LEGACY_CYAN_GLAZED_TERRACOTTA:
			case LEGACY_PURPLE_GLAZED_TERRACOTTA:
			case LEGACY_BLUE_GLAZED_TERRACOTTA:
			case LEGACY_BROWN_GLAZED_TERRACOTTA:
			case LEGACY_GREEN_GLAZED_TERRACOTTA:
			case LEGACY_RED_GLAZED_TERRACOTTA:
			case LEGACY_BLACK_GLAZED_TERRACOTTA:
				return 1.4F;
			case LEGACY_BOOKSHELF:
				return 1.5F;
			case LEGACY_CONCRETE:
				return 1.8F;
			case LEGACY_LOG:
			case LEGACY_CAULDRON:
			case LEGACY_LOG_2:
			case LEGACY_BONE_BLOCK:
			case LEGACY_WHITE_SHULKER_BOX:
			case LEGACY_ORANGE_SHULKER_BOX:
			case LEGACY_MAGENTA_SHULKER_BOX:
			case LEGACY_LIGHT_BLUE_SHULKER_BOX:
			case LEGACY_YELLOW_SHULKER_BOX:
			case LEGACY_LIME_SHULKER_BOX:
			case LEGACY_PINK_SHULKER_BOX:
			case LEGACY_GRAY_SHULKER_BOX:
			case LEGACY_SILVER_SHULKER_BOX:
			case LEGACY_CYAN_SHULKER_BOX:
			case LEGACY_PURPLE_SHULKER_BOX:
			case LEGACY_BLUE_SHULKER_BOX:
			case LEGACY_BROWN_SHULKER_BOX:
			case LEGACY_GREEN_SHULKER_BOX:
			case LEGACY_RED_SHULKER_BOX:
			case LEGACY_BLACK_SHULKER_BOX:
			case LEGACY_CAULDRON_ITEM:
				return 2.0F;
			case LEGACY_CHEST:
			case LEGACY_WORKBENCH:
			case LEGACY_TRAPPED_CHEST:
				return 2.5F;
			case LEGACY_WOOD:
			case LEGACY_GOLD_ORE:
			case LEGACY_IRON_ORE:
			case LEGACY_COAL_ORE:
			case LEGACY_LAPIS_ORE:
			case LEGACY_LAPIS_BLOCK:
			case LEGACY_WOOD_STAIRS:
			case LEGACY_DIAMOND_ORE:
			case LEGACY_WOODEN_DOOR:
			case LEGACY_REDSTONE_ORE:
			case LEGACY_GLOWING_REDSTONE_ORE:
			case LEGACY_FENCE:
			case LEGACY_TRAP_DOOR:
			case LEGACY_FENCE_GATE:
			case LEGACY_WOOD_DOUBLE_STEP:
			case LEGACY_WOOD_STEP:
			case LEGACY_COCOA:
			case LEGACY_EMERALD_ORE:
			case LEGACY_SPRUCE_WOOD_STAIRS:
			case LEGACY_BIRCH_WOOD_STAIRS:
			case LEGACY_JUNGLE_WOOD_STAIRS:
			case LEGACY_BEACON:
			case LEGACY_QUARTZ_ORE:
			case LEGACY_ACACIA_STAIRS:
			case LEGACY_DARK_OAK_STAIRS:
			case LEGACY_SPRUCE_FENCE_GATE:
			case LEGACY_BIRCH_FENCE_GATE:
			case LEGACY_JUNGLE_FENCE_GATE:
			case LEGACY_DARK_OAK_FENCE_GATE:
			case LEGACY_ACACIA_FENCE_GATE:
			case LEGACY_SPRUCE_FENCE:
			case LEGACY_BIRCH_FENCE:
			case LEGACY_JUNGLE_FENCE:
			case LEGACY_DARK_OAK_FENCE:
			case LEGACY_ACACIA_FENCE:
			case LEGACY_SPRUCE_DOOR:
			case LEGACY_BIRCH_DOOR:
			case LEGACY_JUNGLE_DOOR:
			case LEGACY_ACACIA_DOOR:
			case LEGACY_DARK_OAK_DOOR:
			case LEGACY_OBSERVER:
			case LEGACY_WOOD_DOOR:
			case LEGACY_SPRUCE_DOOR_ITEM:
			case LEGACY_BIRCH_DOOR_ITEM:
			case LEGACY_JUNGLE_DOOR_ITEM:
			case LEGACY_ACACIA_DOOR_ITEM:
			case LEGACY_DARK_OAK_DOOR_ITEM:
				return 3.0F;
			case LEGACY_DISPENSER:
			case LEGACY_FURNACE:
			case LEGACY_DROPPER:
				return 3.5F;
			case LEGACY_WEB:
				return 4.0F;
			case LEGACY_STAINED_CLAY:
			case LEGACY_HARD_CLAY:
				return 4.2F;
			case LEGACY_HOPPER:
				return 4.8F;
			case LEGACY_MOB_SPAWNER:
			case LEGACY_IRON_DOOR_BLOCK:
			case LEGACY_IRON_TRAPDOOR:
			case LEGACY_IRON_DOOR:
				return 5.0F;
			case LEGACY_STONE:
			case LEGACY_COBBLESTONE:
			case LEGACY_GOLD_BLOCK:
			case LEGACY_IRON_BLOCK:
			case LEGACY_DOUBLE_STEP:
			case LEGACY_STEP:
			case LEGACY_BRICK:
			case LEGACY_MOSSY_COBBLESTONE:
			case LEGACY_DIAMOND_BLOCK:
			case LEGACY_COBBLESTONE_STAIRS:
			case LEGACY_JUKEBOX:
			case LEGACY_SMOOTH_BRICK:
			case LEGACY_IRON_FENCE:
			case LEGACY_BRICK_STAIRS:
			case LEGACY_SMOOTH_STAIRS:
			case LEGACY_NETHER_BRICK:
			case LEGACY_NETHER_FENCE:
			case LEGACY_NETHER_BRICK_STAIRS:
			case LEGACY_EMERALD_BLOCK:
			case LEGACY_COBBLE_WALL:
			case LEGACY_REDSTONE_BLOCK:
			case LEGACY_PRISMARINE:
			case LEGACY_COAL_BLOCK:
			case LEGACY_DOUBLE_STONE_SLAB2:
			case LEGACY_STONE_SLAB2:
			case LEGACY_PURPUR_BLOCK:
			case LEGACY_PURPUR_PILLAR:
			case LEGACY_PURPUR_STAIRS:
			case LEGACY_PURPUR_DOUBLE_SLAB:
			case LEGACY_PURPUR_SLAB:
			case LEGACY_RED_NETHER_BRICK:
				return 6.0F;
			case LEGACY_ENDER_STONE:
			case LEGACY_DRAGON_EGG:
				return 9.0F;
			case LEGACY_WATER:
			case LEGACY_STATIONARY_WATER:
			case LEGACY_LAVA:
			case LEGACY_STATIONARY_LAVA:
				return 100.0F;
			case LEGACY_ENDER_CHEST:
				return 600.0F;
			case LEGACY_OBSIDIAN:
			case LEGACY_ENCHANTMENT_TABLE:
			case LEGACY_ANVIL:
				return 1200.0F;
			case LEGACY_BEDROCK:
			case LEGACY_ENDER_PORTAL:
			case LEGACY_ENDER_PORTAL_FRAME:
			case LEGACY_COMMAND:
			case LEGACY_END_GATEWAY:
			case LEGACY_COMMAND_REPEATING:
			case LEGACY_COMMAND_CHAIN:
			case LEGACY_STRUCTURE_BLOCK:
				return 3600000.0F;
			case LEGACY_BARRIER:
				return 3600000.8F;
			default:
				return 0;
			// </editor-fold>
			}
		}
	}

}
