name: AdditionsAPI
version: 1.3.0
main: com.chrismin13.additionsapi.AdditionsAPI
author: chrismin13
api-version: 1.13

commands:
  additions:
    description: Main Command of the Additions API.
    usage: /<command>
    permission: additionsapi
    permission-message: You don't have permission to use this command!